/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MarginaliaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// models/Annotation.ts
function createAnnotation(selectedText, position, content = "") {
  const now = new Date().toISOString();
  return {
    annotation_id: generateId(),
    selected_text: selectedText,
    position,
    created: now,
    updated: now,
    content
  };
}
function updateAnnotation(annotation, content) {
  return {
    ...annotation,
    content,
    updated: new Date().toISOString()
  };
}
function generateId() {
  return `anno_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}
function parseAnnotations(content) {
  const annotations = [];
  const yamlRegex = /---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*?)(?=\n---|$)/g;
  let match;
  while ((match = yamlRegex.exec(content)) !== null) {
    try {
      const yamlContent = match[1];
      const markdownContent = match[2].trim();
      const annotation = parseYamlFrontmatter(yamlContent, markdownContent);
      if (annotation) {
        annotations.push(annotation);
      }
    } catch (e) {
      console.error("Failed to parse annotation:", e);
    }
  }
  if (annotations.length === 0) {
    const separatorRegex = /<!-- ANNOTATION_START ([\s\S]*?) -->\s*\n([\s\S]*?)(?=\n<!-- ANNOTATION_END|$)/g;
    while ((match = separatorRegex.exec(content)) !== null) {
      try {
        const metadata = JSON.parse(match[1]);
        const markdownContent = match[2].trim();
        annotations.push({
          annotation_id: metadata.annotation_id,
          selected_text: metadata.selected_text,
          position: metadata.position,
          created: metadata.created,
          updated: metadata.updated,
          content: markdownContent
        });
      } catch (e) {
        console.error("Failed to parse annotation with separator:", e);
      }
    }
  }
  return annotations;
}
function parseYamlFrontmatter(yaml, content) {
  const lines = yaml.split("\n");
  const metadata = {};
  for (const line of lines) {
    const colonIndex = line.indexOf(":");
    if (colonIndex > 0) {
      const key = line.substring(0, colonIndex).trim();
      const value = line.substring(colonIndex + 1).trim();
      if (key === "position") {
        try {
          metadata[key] = JSON.parse(value);
        } catch (e) {
          metadata[key] = {};
        }
      } else {
        metadata[key] = value;
      }
    }
  }
  if (!metadata.annotation_id)
    return null;
  return {
    annotation_id: metadata.annotation_id,
    selected_text: metadata.selected_text || "",
    position: metadata.position || {},
    created: metadata.created || new Date().toISOString(),
    updated: metadata.updated || new Date().toISOString(),
    content
  };
}
function serializeAnnotations(annotations) {
  if (annotations.length === 0)
    return "";
  return annotations.map((anno) => {
    return `---
annotation_id: ${anno.annotation_id}
selected_text: ${escapeYaml(anno.selected_text)}
position: ${JSON.stringify(anno.position)}
created: ${anno.created}
updated: ${anno.updated}
---

${anno.content}
`;
  }).join("\n---\n\n");
}
function escapeYaml(str) {
  if (str.includes(":") || str.includes("#") || str.includes("\n") || str.includes('"')) {
    return `"${str.replace(/"/g, '\\"')}"`;
  }
  return str;
}

// settings.ts
var DEFAULT_SETTINGS = {
  annotationFolder: "_annotations",
  autoShowSidebar: true,
  highlightColor: "rgba(255, 255, 0, 0.3)",
  mobileEnabled: true
};

// utils/fileUtils.ts
var import_obsidian = require("obsidian");
function getAnnotationFilePath(sourceFile, annotationFolder) {
  const baseName = sourceFile.basename;
  return (0, import_obsidian.normalizePath)(`${annotationFolder}/${baseName}-annotation.md`);
}
async function ensureAnnotationFolder(vault, folderPath) {
  const normalizedPath = (0, import_obsidian.normalizePath)(folderPath);
  const existingFolder = vault.getAbstractFileByPath(normalizedPath);
  if (existingFolder instanceof import_obsidian.TFolder) {
    return existingFolder;
  }
  await vault.createFolder(normalizedPath);
  const createdFolder = vault.getAbstractFileByPath(normalizedPath);
  if (createdFolder instanceof import_obsidian.TFolder) {
    return createdFolder;
  }
  throw new Error(`Failed to create annotation folder: ${normalizedPath}`);
}
async function loadAnnotations(vault, sourceFile, annotationFolder) {
  const annotationPath = getAnnotationFilePath(sourceFile, annotationFolder);
  const file = vault.getAbstractFileByPath(annotationPath);
  if (!(file instanceof import_obsidian.TFile)) {
    return [];
  }
  try {
    const content = await vault.read(file);
    return parseAnnotations(content);
  } catch (error) {
    console.error("Failed to load annotations:", error);
    return [];
  }
}
async function saveAnnotations(vault, sourceFile, annotationFolder, annotations) {
  const annotationPath = getAnnotationFilePath(sourceFile, annotationFolder);
  if (annotations.length === 0) {
    const existingFile2 = vault.getAbstractFileByPath(annotationPath);
    if (existingFile2 instanceof import_obsidian.TFile) {
      await vault.delete(existingFile2);
    }
    return;
  }
  await ensureAnnotationFolder(vault, annotationFolder);
  const content = serializeAnnotations(annotations);
  const existingFile = vault.getAbstractFileByPath(annotationPath);
  if (existingFile instanceof import_obsidian.TFile) {
    await vault.modify(existingFile, content);
  } else {
    await vault.create(annotationPath, content);
  }
}
async function addAnnotation(vault, sourceFile, annotationFolder, annotation) {
  const annotations = await loadAnnotations(vault, sourceFile, annotationFolder);
  annotations.push(annotation);
  await saveAnnotations(vault, sourceFile, annotationFolder, annotations);
}
async function updateAnnotation2(vault, sourceFile, annotationFolder, annotation) {
  const annotations = await loadAnnotations(vault, sourceFile, annotationFolder);
  const index = annotations.findIndex((a) => a.annotation_id === annotation.annotation_id);
  if (index !== -1) {
    annotations[index] = annotation;
    await saveAnnotations(vault, sourceFile, annotationFolder, annotations);
  }
}
async function deleteAnnotation(vault, sourceFile, annotationFolder, annotationId) {
  const annotations = await loadAnnotations(vault, sourceFile, annotationFolder);
  const filtered = annotations.filter((a) => a.annotation_id !== annotationId);
  await saveAnnotations(vault, sourceFile, annotationFolder, filtered);
}
function getAnnotationFile(vault, sourceFile, annotationFolder) {
  const annotationPath = getAnnotationFilePath(sourceFile, annotationFolder);
  const file = vault.getAbstractFileByPath(annotationPath);
  return file instanceof import_obsidian.TFile ? file : null;
}

// utils/locationUtils.ts
function getPositionFromDOMSelection(filePath, selection) {
  var _a;
  if (!selection.rangeCount)
    return null;
  const range = selection.getRangeAt(0);
  const container = range.startContainer;
  let lineNumber = 0;
  let element = container.nodeType === Node.TEXT_NODE ? container.parentElement : container;
  while (element) {
    const lineAttr = element.getAttribute("data-line");
    if (lineAttr) {
      lineNumber = parseInt(lineAttr, 10);
      break;
    }
    element = element.parentElement;
  }
  let offset = 0;
  const walker = document.createTreeWalker(
    document.body,
    NodeFilter.SHOW_TEXT
  );
  let node;
  while ((node = walker.nextNode()) !== null) {
    if (node === container || node.contains(container)) {
      offset += range.startOffset;
      break;
    }
    offset += ((_a = node.textContent) == null ? void 0 : _a.length) || 0;
  }
  return {
    file_path: filePath,
    offset,
    line_number: lineNumber
  };
}

// processors/AnnotationHighlighter.ts
var MARGINALIA_HIGHLIGHT_CLASS = "marginalia-highlight";
var MARGINALIA_HIGHLIGHT_ACTIVE_CLASS = "marginalia-highlight-active";
function processHighlights(element, annotations, highlightColor) {
  if (annotations.length === 0)
    return;
  for (const annotation of annotations) {
    try {
      highlightText(element, annotation, highlightColor);
    } catch (error) {
      console.error(`[Marginalia] Failed to highlight annotation ${annotation.annotation_id}:`, error);
    }
  }
}
function highlightText(container, annotation, highlightColor) {
  var _a, _b;
  const targetText = annotation.selected_text;
  if (!targetText || targetText.trim().length === 0)
    return;
  const existingHighlight = getHighlightElement(container, annotation.annotation_id);
  if (existingHighlight)
    return;
  const walker = document.createTreeWalker(
    container,
    NodeFilter.SHOW_TEXT,
    null
  );
  const nodesToHighlight = [];
  let node;
  while ((node = walker.nextNode()) !== null) {
    const textNode = node;
    const parent = textNode.parentElement;
    if (((_a = parent == null ? void 0 : parent.classList) == null ? void 0 : _a.contains(MARGINALIA_HIGHLIGHT_CLASS)) || (parent == null ? void 0 : parent.closest("code, pre, .code-block"))) {
      continue;
    }
    if ((_b = textNode.textContent) == null ? void 0 : _b.includes(targetText)) {
      nodesToHighlight.push(textNode);
    }
  }
  for (const textNode of nodesToHighlight) {
    const text = textNode.textContent || "";
    const index = text.indexOf(targetText);
    if (index !== -1) {
      wrapTextWithHighlight(textNode, index, targetText.length, annotation, highlightColor);
      break;
    }
  }
}
function wrapTextWithHighlight(textNode, startIndex, length, annotation, highlightColor) {
  const parent = textNode.parentNode;
  if (!parent)
    return;
  const text = textNode.textContent || "";
  const beforeText = text.substring(0, startIndex);
  const highlightedText = text.substring(startIndex, startIndex + length);
  const afterText = text.substring(startIndex + length);
  const highlightSpan = document.createElement("span");
  highlightSpan.className = MARGINALIA_HIGHLIGHT_CLASS;
  highlightSpan.dataset.annotationId = annotation.annotation_id;
  highlightSpan.style.backgroundColor = highlightColor;
  highlightSpan.textContent = highlightedText;
  if (beforeText) {
    parent.insertBefore(document.createTextNode(beforeText), textNode);
  }
  parent.insertBefore(highlightSpan, textNode);
  if (afterText) {
    parent.insertBefore(document.createTextNode(afterText), textNode);
  }
  parent.removeChild(textNode);
  console.log(`[Marginalia] Highlighted text: "${highlightedText.substring(0, 30)}..."`);
}
function updateHighlightColor(element, color) {
  const highlights = element.querySelectorAll(`.${MARGINALIA_HIGHLIGHT_CLASS}`);
  for (const highlight of Array.from(highlights)) {
    highlight.style.backgroundColor = color;
  }
}
function getHighlightElement(container, annotationId) {
  return container.querySelector(
    `[data-annotation-id="${annotationId}"].${MARGINALIA_HIGHLIGHT_CLASS}`
  );
}
function injectHighlightIntoElement(container, annotation, highlightColor) {
  var _a, _b;
  console.log(`[Marginalia] Injecting highlight for: ${annotation.annotation_id}`);
  console.log(`[Marginalia] Target text: "${annotation.selected_text}"`);
  console.log(`[Marginalia] Container className:`, container.className);
  console.log(`[Marginalia] Container innerHTML (first 200 chars):`, (_a = container.innerHTML) == null ? void 0 : _a.substring(0, 200));
  const existingHighlight = getHighlightElement(container, annotation.annotation_id);
  if (existingHighlight) {
    console.log(`[Marginalia] Highlight already exists, skipping`);
    return;
  }
  let targetText = annotation.selected_text;
  if (!targetText || targetText.trim().length === 0) {
    console.warn(`[Marginalia] Empty target text, skipping`);
    return;
  }
  const walker = document.createTreeWalker(
    container,
    NodeFilter.SHOW_TEXT,
    null
  );
  const allTextNodes = [];
  const nodesToHighlight = [];
  let node;
  while ((node = walker.nextNode()) !== null) {
    const textNode = node;
    allTextNodes.push(textNode);
    const parent = textNode.parentElement;
    if (((_b = parent == null ? void 0 : parent.classList) == null ? void 0 : _b.contains(MARGINALIA_HIGHLIGHT_CLASS)) || (parent == null ? void 0 : parent.closest("code, pre, .code-block"))) {
      continue;
    }
    const nodeText = textNode.textContent || "";
    if (nodeText.includes(targetText)) {
      nodesToHighlight.push(textNode);
    }
  }
  console.log(`[Marginalia] Total text nodes: ${allTextNodes.length}`);
  console.log(`[Marginalia] Matching text nodes: ${nodesToHighlight.length}`);
  if (nodesToHighlight.length === 0) {
    console.log(`[Marginalia] All text node contents:`);
    allTextNodes.forEach((n, i) => {
      var _a2;
      const text = (_a2 = n.textContent) == null ? void 0 : _a2.trim();
      if (text) {
        console.log(`  [${i}] "${text.substring(0, 50)}"`);
      }
    });
  }
  let injected = false;
  for (const textNode of nodesToHighlight) {
    const text = textNode.textContent || "";
    const index = text.indexOf(targetText);
    if (index !== -1) {
      wrapTextWithHighlight(textNode, index, targetText.length, annotation, highlightColor);
      injected = true;
      console.log(`[Marginalia] Successfully injected highlight at index ${index}`);
      break;
    }
  }
  if (!injected) {
    console.warn(`[Marginalia] Failed to inject highlight - text not found in container`);
    const normalizedTarget = targetText.replace(/\s+/g, "");
    if (normalizedTarget.length > 0) {
      console.log(`[Marginalia] Trying normalized match...`);
      walker.currentNode = container;
      let retryNode;
      while ((retryNode = walker.nextNode()) !== null) {
        const textNode = retryNode;
        const nodeText = (textNode.textContent || "").replace(/\s+/g, "");
        if (nodeText.includes(normalizedTarget)) {
          console.log(`[Marginalia] Found normalized match!`);
          const originalText = textNode.textContent || "";
          const originalIndex = originalText.indexOf(targetText.trim());
          if (originalIndex >= 0) {
            wrapTextWithHighlight(textNode, originalIndex, targetText.length, annotation, highlightColor);
            injected = true;
            break;
          }
        }
      }
    }
  }
}

// views/AnnotationSidebarView.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_ANNOTATION_SIDEBAR = "annotation-sidebar";
var AnnotationSidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, vault, settings, onAnnotationClick, onAnnotationEdit, onAnnotationDelete, onGotoSource) {
    super(leaf);
    this.currentFile = null;
    this.annotations = [];
    this.editingAnnotationId = null;
    this.isEditMode = false;
    this.vault = vault;
    this.settings = settings;
    this.onAnnotationClick = onAnnotationClick;
    this.onAnnotationEdit = onAnnotationEdit;
    this.onAnnotationDelete = onAnnotationDelete;
    this.onGotoSource = onGotoSource;
  }
  getViewType() {
    return VIEW_TYPE_ANNOTATION_SIDEBAR;
  }
  getDisplayText() {
    return "\u6279\u6CE8";
  }
  getIcon() {
    return "highlighter";
  }
  async onOpen() {
    this.containerEl.addClass("marginalia-sidebar");
    await this.render();
  }
  async onClose() {
  }
  /**
   * 设置当前文件并刷新视图
   */
  async setFile(file) {
    this.currentFile = file;
    if (file) {
      this.annotations = await loadAnnotations(this.vault, file, this.settings.annotationFolder);
    } else {
      this.annotations = [];
    }
    await this.render();
  }
  /**
   * 获取当前批注
   */
  getAnnotations() {
    return this.annotations;
  }
  /**
   * 刷新视图
   */
  async refresh() {
    if (this.currentFile) {
      this.annotations = await loadAnnotations(
        this.vault,
        this.currentFile,
        this.settings.annotationFolder
      );
      await this.render();
    }
  }
  /**
   * 设置编辑模式状态
   */
  setEditMode(isEditMode) {
    this.isEditMode = isEditMode;
    this.render();
  }
  /**
   * 更新设置
   */
  updateSettings(settings) {
    this.settings = settings;
    this.refresh();
  }
  /**
   * 渲染侧边栏内容
   */
  async render() {
    const content = this.containerEl.querySelector(".view-content");
    if (!content)
      return;
    content.empty();
    const header = content.createDiv("marginalia-sidebar-header");
    header.createEl("h3", { text: "\u6279\u6CE8\u5217\u8868" });
    header.createSpan({
      text: `${this.annotations.length} \u6761\u6279\u6CE8`,
      cls: "marginalia-sidebar-count"
    });
    const container = content.createDiv("marginalia-sidebar-container");
    if (this.isEditMode) {
      const editModePlaceholder = container.createDiv("marginalia-edit-mode-placeholder");
      editModePlaceholder.createEl("p", {
        text: "\u{1F4DD} \u7F16\u8F91\u6A21\u5F0F\u4E0D\u5C55\u793A\u6279\u6CE8\u5185\u5BB9",
        cls: "marginalia-edit-mode-text"
      });
      editModePlaceholder.createEl("p", {
        text: "\u5207\u6362\u5230\u9884\u89C8\u6A21\u5F0F\u67E5\u770B\u6279\u6CE8",
        cls: "marginalia-edit-mode-hint"
      });
      return;
    }
    if (this.annotations.length === 0) {
      const emptyState = container.createDiv("marginalia-empty-state");
      emptyState.createEl("p", { text: "\u6682\u65E0\u6279\u6CE8" });
      emptyState.createEl("p", {
        text: import_obsidian2.Platform.isMobile ? "\u9009\u4E2D\u6587\u672C\u6DFB\u52A0\u6279\u6CE8" : "\u9009\u4E2D\u6587\u672C\u540E\u53F3\u952E\u6DFB\u52A0\u6279\u6CE8",
        cls: "marginalia-empty-hint"
      });
      return;
    }
    const sortedAnnotations = [...this.annotations].sort(
      (a, b) => {
        var _a, _b;
        return (((_a = a.position) == null ? void 0 : _a.offset) || 0) - (((_b = b.position) == null ? void 0 : _b.offset) || 0);
      }
    );
    for (const annotation of sortedAnnotations) {
      await this.createAnnotationCard(container, annotation);
    }
  }
  /**
   * 创建单个批注卡片
   */
  async createAnnotationCard(container, annotation) {
    const card = container.createDiv("marginalia-annotation-card");
    card.dataset.annotationId = annotation.annotation_id;
    const sourceTextEl = card.createDiv("marginalia-card-source");
    sourceTextEl.createEl("blockquote", {
      text: annotation.selected_text.length > 150 ? annotation.selected_text.substring(0, 150) + "..." : annotation.selected_text
    });
    const contentEl = card.createDiv("marginalia-card-content markdown-rendered");
    if (this.editingAnnotationId === annotation.annotation_id) {
      const textarea = contentEl.createEl("textarea");
      textarea.value = annotation.content;
      textarea.className = "marginalia-card-edit-textarea";
      textarea.placeholder = "\u8F93\u5165\u6279\u6CE8\u5185\u5BB9...";
      textarea.onblur = async () => {
        const newContent = textarea.value;
        if (newContent !== annotation.content) {
          await this.onAnnotationEdit(annotation, newContent);
          annotation.content = newContent;
          annotation.updated = new Date().toISOString();
        }
        this.editingAnnotationId = null;
        await this.render();
      };
      setTimeout(() => textarea.focus(), 100);
    } else {
      if (annotation.content) {
        await import_obsidian2.MarkdownRenderer.render(
          this.app,
          annotation.content,
          contentEl,
          "",
          this
        );
      } else {
        contentEl.createEl("em", {
          text: "\u6682\u65E0\u5185\u5BB9",
          cls: "marginalia-empty-content"
        });
      }
    }
    const footerEl = card.createDiv("marginalia-card-footer");
    const metaEl = footerEl.createDiv("marginalia-card-meta");
    const date = new Date(annotation.created);
    const yy = date.getFullYear().toString().slice(-2);
    const MM = String(date.getMonth() + 1).padStart(2, "0");
    const dd = String(date.getDate()).padStart(2, "0");
    const HH = String(date.getHours()).padStart(2, "0");
    const mm = String(date.getMinutes()).padStart(2, "0");
    metaEl.createSpan({
      text: `${yy}-${MM}-${dd} ${HH}:${mm}`,
      cls: "marginalia-card-time"
    });
    const actionsEl = footerEl.createDiv("marginalia-card-actions");
    const editBtn = actionsEl.createEl("button", {
      cls: "marginalia-btn marginalia-btn-small",
      attr: { title: "\u7F16\u8F91\u6279\u6CE8" }
    });
    editBtn.innerHTML = "\u270F\uFE0F";
    editBtn.onclick = (e) => {
      e.stopPropagation();
      this.editingAnnotationId = annotation.annotation_id;
      this.render();
    };
    const deleteBtn = actionsEl.createEl("button", {
      cls: "marginalia-btn marginalia-btn-small marginalia-btn-danger",
      attr: { title: "\u5220\u9664\u6279\u6CE8" }
    });
    deleteBtn.innerHTML = "\u{1F5D1}\uFE0F";
    deleteBtn.onclick = (e) => {
      e.stopPropagation();
      this.onAnnotationDelete(annotation.annotation_id);
    };
    card.addEventListener("click", async (e) => {
      const target = e.target;
      if (target.tagName === "TEXTAREA" || target.tagName === "BUTTON" || target.closest("button")) {
        return;
      }
      this.highlightAnnotationCard(annotation.annotation_id);
      await this.onAnnotationClick(annotation);
    });
  }
  /**
   * 高亮指定批注卡片
   */
  highlightAnnotationCard(annotationId) {
    this.containerEl.querySelectorAll(".marginalia-annotation-card.active").forEach((el) => el.classList.remove("active"));
    const card = this.containerEl.querySelector(
      `.marginalia-annotation-card[data-annotation-id="${annotationId}"]`
    );
    if (card) {
      card.classList.add("active");
      card.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }
};

// main.ts
var MarginaliaPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.sidebarView = null;
    this.activeFile = null;
    this.annotationCache = /* @__PURE__ */ new Map();
    this.floatingCard = null;
    this.contextMenu = null;
    this.mobileSelectionMenu = null;
    this.currentEditAnnotationId = null;
  }
  async onload() {
    console.log("\u52A0\u8F7D Obsidian \u6279\u6CE8\u63D2\u4EF6");
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_ANNOTATION_SIDEBAR,
      (leaf) => new AnnotationSidebarView(
        leaf,
        this.app.vault,
        this.settings,
        this.handleAnnotationClick.bind(this),
        this.handleAnnotationEdit.bind(this),
        this.handleAnnotationDelete.bind(this),
        this.handleGotoSource.bind(this)
      )
    );
    this.addRibbonIcon("highlighter", "\u5207\u6362\u6279\u6CE8\u4FA7\u8FB9\u680F", () => {
      this.toggleSidebar();
    });
    this.addCommand({
      id: "create-annotation",
      name: "\u521B\u5EFA\u6279\u6CE8",
      editorCallback: (editor, view) => {
        this.createAnnotationFromEditor(view.file, editor);
      }
    });
    this.addCommand({
      id: "toggle-annotation-sidebar",
      name: "\u5207\u6362\u6279\u6CE8\u4FA7\u8FB9\u680F",
      callback: () => this.toggleSidebar()
    });
    this.registerMarkdownPostProcessor(
      this.highlightPostProcessor.bind(this)
    );
    this.registerActiveLeafChange();
    this.registerContextMenu();
    this.registerClickHandlers();
    this.registerMobileHandlers();
    this.addSettingTab(new MarginaliaSettingTab(this.app, this));
    if (this.settings.autoShowSidebar) {
      this.initSidebar();
    }
  }
  onunload() {
    console.log("\u5378\u8F7D Obsidian \u6279\u6CE8\u63D2\u4EF6");
    this.closeFloatingCard();
    this.closeContextMenu();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    (_a = this.sidebarView) == null ? void 0 : _a.updateSettings(this.settings);
  }
  /**
   * 注册活动标签页变更事件
   */
  registerActiveLeafChange() {
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", async (leaf) => {
        if ((leaf == null ? void 0 : leaf.view) instanceof import_obsidian3.MarkdownView) {
          const file = leaf.view.file;
          if (file && file.extension === "md") {
            this.activeFile = file;
            await this.updateSidebarForFile(file);
            await this.refreshHighlightsForActiveFile();
          }
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", async () => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (markdownView && markdownView.file) {
          console.log("[Marginalia] Layout changed, mode:", markdownView.getMode());
          this.activeFile = markdownView.file;
          if (markdownView.getMode() === "source") {
            console.log("[Marginalia] Switched to edit mode");
            if (this.sidebarView) {
              this.sidebarView.setEditMode(true);
            } else if (this.settings.autoShowSidebar) {
              await this.initSidebar();
              await this.updateSidebarForFile(this.activeFile);
              if (this.sidebarView) {
                this.sidebarView.setEditMode(true);
              }
            }
          } else if (markdownView.getMode() === "preview") {
            console.log("[Marginalia] Switched to preview mode, showing annotations");
            if (this.sidebarView) {
              const sidebar = this.sidebarView;
              sidebar.setEditMode(false);
              await sidebar.refresh();
            } else if (this.settings.autoShowSidebar) {
              await this.initSidebar();
              await this.updateSidebarForFile(this.activeFile);
              if (this.sidebarView) {
                this.sidebarView.setEditMode(false);
              }
            }
            setTimeout(async () => {
              var _a;
              await this.refreshHighlightsForActiveFile();
              (_a = markdownView.previewMode) == null ? void 0 : _a.rerender(true);
            }, 100);
          }
        }
      })
    );
  }
  /**
   * 注册右键菜单（PC端）
   */
  registerContextMenu() {
    if (import_obsidian3.Platform.isMobile)
      return;
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        if (!(view instanceof import_obsidian3.MarkdownView))
          return;
        if (view.getMode() !== "preview")
          return;
        const selectedText = editor.getSelection();
        if (!selectedText || selectedText.trim().length === 0)
          return;
        menu.addItem((item) => {
          item.setTitle("\u{1F58A} \u6DFB\u52A0\u6279\u6CE8").setIcon("highlighter").onClick(() => {
            this.createAnnotationFromEditor(view.file, editor);
          });
        });
      })
    );
    this.registerDomEvent(document, "contextmenu", (evt) => {
      const selection = window.getSelection();
      if (!selection || selection.toString().trim().length === 0)
        return;
      const target = evt.target;
      const container = target.closest(".markdown-preview-view");
      if (!container)
        return;
      const highlight = target.closest(`.${MARGINALIA_HIGHLIGHT_CLASS}`);
      if (highlight)
        return;
      evt.preventDefault();
      this.showContextMenu(evt.clientX, evt.clientY, selection.toString(), container);
    });
  }
  /**
   * 注册点击事件处理器
   */
  registerClickHandlers() {
    this.registerDomEvent(document, "dblclick", (evt) => {
      const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (!markdownView || markdownView.getMode() !== "preview")
        return;
      const target = evt.target;
      const highlight = target.closest(`.${MARGINALIA_HIGHLIGHT_CLASS}`);
      if (highlight) {
        const annotationId = highlight.dataset.annotationId;
        if (annotationId && this.activeFile) {
          evt.preventDefault();
          evt.stopPropagation();
          this.showFloatingCard(annotationId, highlight);
        }
      }
    });
    this.registerDomEvent(document, "click", async (evt) => {
      var _a;
      const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (!markdownView || markdownView.getMode() !== "preview")
        return;
      const target = evt.target;
      const highlight = target.closest(`.${MARGINALIA_HIGHLIGHT_CLASS}`);
      if (highlight) {
        const annotationId = highlight.dataset.annotationId;
        if (annotationId && this.activeFile) {
          console.log(`[Marginalia] Clicked highlight: ${annotationId}`);
          (_a = this.sidebarView) == null ? void 0 : _a.highlightAnnotationCard(annotationId);
          await this.activateHighlightInDocument(annotationId);
        }
      }
    });
    this.registerDomEvent(document, "click", (evt) => {
      if (!evt.ctrlKey && !evt.metaKey)
        return;
      const target = evt.target;
      const highlight = target.closest(`.${MARGINALIA_HIGHLIGHT_CLASS}`);
      if (highlight) {
        const annotationId = highlight.dataset.annotationId;
        if (annotationId && this.activeFile) {
          evt.preventDefault();
          evt.stopPropagation();
          const annotations = this.annotationCache.get(this.activeFile.path) || [];
          const annotation = annotations.find((a) => a.annotation_id === annotationId);
          if (annotation) {
            this.handleGotoAnnotationFile(annotation);
          }
        }
      }
    });
  }
  /**
   * 注册移动端特定处理器
   */
  registerMobileHandlers() {
    if (!import_obsidian3.Platform.isMobile || !this.settings.mobileEnabled)
      return;
    this.registerDomEvent(document, "selectionchange", (0, import_obsidian3.debounce)(() => {
      const selection = window.getSelection();
      if (!selection || selection.toString().trim().length === 0) {
        this.closeMobileSelectionMenu();
        return;
      }
      const range = selection.getRangeAt(0);
      const rect = range.getBoundingClientRect();
      this.showMobileSelectionMenu(
        rect.left + rect.width / 2,
        rect.top - 50,
        selection.toString()
      );
    }, 300));
    this.registerDomEvent(document, "scroll", () => {
      this.closeMobileSelectionMenu();
    });
  }
  /**
   * 初始化侧边栏
   */
  async initSidebar() {
    const { workspace } = this.app;
    const existingLeaf = workspace.getLeavesOfType(VIEW_TYPE_ANNOTATION_SIDEBAR)[0];
    if (existingLeaf)
      return;
    const rightLeaf = workspace.getRightLeaf(false);
    if (!rightLeaf)
      return;
    await rightLeaf.setViewState({
      type: VIEW_TYPE_ANNOTATION_SIDEBAR,
      active: false
    });
    const leaf = workspace.getLeavesOfType(VIEW_TYPE_ANNOTATION_SIDEBAR)[0];
    if (leaf) {
      this.sidebarView = leaf.view;
      if (this.activeFile) {
        await this.sidebarView.setFile(this.activeFile);
      }
    }
  }
  /**
   * 切换侧边栏显示
   */
  async toggleSidebar() {
    const { workspace } = this.app;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_ANNOTATION_SIDEBAR);
    if (leaves.length > 0) {
      leaves.forEach((leaf) => leaf.detach());
      this.sidebarView = null;
    } else {
      await this.initSidebar();
    }
  }
  /**
   * 隐藏侧边栏
   */
  hideSidebar() {
    const { workspace } = this.app;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_ANNOTATION_SIDEBAR);
    if (leaves.length > 0) {
      leaves.forEach((leaf) => leaf.detach());
      this.sidebarView = null;
    }
  }
  /**
   * 更新侧边栏文件
   */
  async updateSidebarForFile(file) {
    if (!this.sidebarView) {
      if (this.settings.autoShowSidebar) {
        await this.initSidebar();
      }
      return;
    }
    await this.sidebarView.setFile(file);
  }
  /**
   * 刷新当前活动文件的高亮缓存
   */
  async refreshHighlightsForActiveFile() {
    if (!this.activeFile)
      return;
    const annotations = await loadAnnotations(
      this.app.vault,
      this.activeFile,
      this.settings.annotationFolder
    );
    this.annotationCache.set(this.activeFile.path, annotations);
  }
  /**
   * Markdown 后处理器 - 注入高亮
   */
  highlightPostProcessor(element, context) {
    const sourcePath = context.sourcePath;
    const annotations = this.annotationCache.get(sourcePath);
    if (annotations && annotations.length > 0) {
      processHighlights(element, annotations, this.settings.highlightColor);
    }
  }
  /**
   * 从编辑器选区创建批注
   */
  async createAnnotationFromEditor(file, editor) {
    if (!file)
      return;
    const selectedText = editor.getSelection();
    if (!selectedText || selectedText.trim().length === 0) {
      return;
    }
    const cursor = editor.getCursor("from");
    const offset = editor.posToOffset(cursor);
    const lineNumber = cursor.line;
    const position = {
      file_path: file.path,
      offset,
      line_number: lineNumber
    };
    this.showAnnotationModal(file, selectedText, position);
  }
  /**
   * 显示上下文菜单
   */
  showContextMenu(x, y, selectedText, container) {
    this.closeContextMenu();
    const menu = document.createElement("div");
    menu.className = "marginalia-context-menu";
    menu.style.left = `${x}px`;
    menu.style.top = `${y}px`;
    const item = menu.createDiv("marginalia-context-menu-item");
    item.createSpan({ cls: "marginalia-context-menu-item-icon", text: "\u{1F58A}" });
    item.createSpan({ text: "\u6DFB\u52A0\u6279\u6CE8" });
    item.onclick = () => {
      this.closeContextMenu();
      const position = getPositionFromDOMSelection(this.activeFile.path, window.getSelection());
      if (position) {
        this.showAnnotationModal(this.activeFile, selectedText, position);
      }
    };
    document.body.appendChild(menu);
    this.contextMenu = menu;
    setTimeout(() => {
      const closeHandler = (e) => {
        if (!menu.contains(e.target)) {
          this.closeContextMenu();
          document.removeEventListener("click", closeHandler);
        }
      };
      document.addEventListener("click", closeHandler);
    }, 100);
  }
  /**
   * 关闭上下文菜单
   */
  closeContextMenu() {
    if (this.contextMenu) {
      this.contextMenu.remove();
      this.contextMenu = null;
    }
  }
  /**
   * 显示移动端选择菜单
   */
  showMobileSelectionMenu(x, y, selectedText) {
    this.closeMobileSelectionMenu();
    const menu = document.createElement("div");
    menu.className = "marginalia-context-menu";
    menu.style.left = `${Math.min(x, window.innerWidth - 160)}px`;
    menu.style.top = `${Math.max(y, 10)}px`;
    const item = menu.createDiv("marginalia-context-menu-item");
    item.createSpan({ cls: "marginalia-context-menu-item-icon", text: "\u{1F58A}" });
    item.createSpan({ text: "\u6279\u6CE8" });
    item.onclick = () => {
      this.closeMobileSelectionMenu();
      const selection = window.getSelection();
      if (selection) {
        const position = getPositionFromDOMSelection(this.activeFile.path, selection);
        if (position) {
          this.showAnnotationModal(this.activeFile, selectedText, position);
        }
      }
    };
    document.body.appendChild(menu);
    this.mobileSelectionMenu = menu;
  }
  /**
   * 关闭移动端选择菜单
   */
  closeMobileSelectionMenu() {
    if (this.mobileSelectionMenu) {
      this.mobileSelectionMenu.remove();
      this.mobileSelectionMenu = null;
    }
  }
  /**
   * 显示批注输入弹窗
   */
  showAnnotationModal(file, selectedText, position) {
    new AnnotationInputModal(
      this.app,
      selectedText,
      async (content) => {
        var _a;
        const annotation = createAnnotation(selectedText, position, content);
        await addAnnotation(this.app.vault, file, this.settings.annotationFolder, annotation);
        const annotations = this.annotationCache.get(file.path) || [];
        annotations.push(annotation);
        this.annotationCache.set(file.path, annotations);
        this.injectHighlightImmediate(annotation);
        (_a = this.sidebarView) == null ? void 0 : _a.refresh();
      }
    ).open();
  }
  /**
   * 立即注入高亮到当前视图
   * 关键修复：不依赖重新渲染，直接操作DOM
   */
  injectHighlightImmediate(annotation) {
    var _a;
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!markdownView) {
      console.log("[Marginalia] No markdown view found");
      return;
    }
    console.log("[Marginalia] Injecting highlight into markdown view");
    console.log("[Marginalia] View mode:", markdownView.getMode());
    const currentMode = markdownView.getMode();
    if (currentMode !== "preview") {
      console.log("[Marginalia] Not in preview mode, skipping immediate highlight injection");
      console.log("[Marginalia] Highlights will appear when switching to preview mode");
      return;
    }
    const possibleSelectors = [
      ".markdown-preview-view",
      ".markdown-reading-view",
      ".view-content",
      ".markdown-rendered",
      ".markdown-preview-section"
    ];
    let injected = false;
    if ((_a = markdownView.previewMode) == null ? void 0 : _a.containerEl) {
      console.log("[Marginalia] Trying previewMode container");
      injectHighlightIntoElement(
        markdownView.previewMode.containerEl,
        annotation,
        this.settings.highlightColor
      );
      injected = true;
    }
    for (const selector of possibleSelectors) {
      const containers = markdownView.containerEl.querySelectorAll(selector);
      containers.forEach((container) => {
        var _a2;
        if (container instanceof HTMLElement && ((_a2 = container.textContent) == null ? void 0 : _a2.includes(annotation.selected_text))) {
          console.log(`[Marginalia] Trying container: ${selector}`);
          injectHighlightIntoElement(
            container,
            annotation,
            this.settings.highlightColor
          );
          injected = true;
        }
      });
    }
    if (!injected) {
      console.warn("[Marginalia] Could not find suitable container for highlight injection");
    }
  }
  /**
   * 在文档中激活高亮（带脉冲效果）
   */
  async activateHighlightInDocument(annotationId) {
    var _a;
    console.log(`[Marginalia] Activating highlight in document: ${annotationId}`);
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!markdownView) {
      console.warn("[Marginalia] No markdown view found for activation");
      return;
    }
    if (markdownView.getMode() !== "preview") {
      console.warn("[Marginalia] Not in preview mode, cannot activate highlight");
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 50));
    const containers = [];
    if ((_a = markdownView.previewMode) == null ? void 0 : _a.containerEl) {
      containers.push(markdownView.previewMode.containerEl);
    }
    const possibleSelectors = [
      ".markdown-preview-view",
      ".markdown-reading-view",
      ".view-content",
      ".markdown-rendered"
    ];
    for (const selector of possibleSelectors) {
      const el = markdownView.containerEl.querySelector(selector);
      if (el instanceof HTMLElement) {
        containers.push(el);
      }
    }
    for (const container of containers) {
      const highlight = container.querySelector(`[data-annotation-id="${annotationId}"].${MARGINALIA_HIGHLIGHT_CLASS}`);
      if (highlight) {
        console.log("[Marginalia] Found highlight in container, activating and scrolling");
        container.querySelectorAll(`.${MARGINALIA_HIGHLIGHT_ACTIVE_CLASS}`).forEach((el) => el.classList.remove(MARGINALIA_HIGHLIGHT_ACTIVE_CLASS));
        highlight.classList.add(MARGINALIA_HIGHLIGHT_ACTIVE_CLASS);
        highlight.scrollIntoView({ behavior: "smooth", block: "center" });
        console.log("[Marginalia] Successfully scrolled to highlight");
        return;
      }
    }
    console.warn(`[Marginalia] Highlight element not found in any container: ${annotationId}`);
  }
  /**
   * 显示悬浮卡片
   */
  async showFloatingCard(annotationId, highlightElement) {
    var _a;
    if (!this.activeFile)
      return;
    const annotations = this.annotationCache.get(this.activeFile.path) || [];
    const annotation = annotations.find((a) => a.annotation_id === annotationId);
    if (!annotation)
      return;
    this.closeFloatingCard();
    this.currentEditAnnotationId = annotationId;
    const card = document.createElement("div");
    card.className = "marginalia-floating-card";
    const rect = highlightElement.getBoundingClientRect();
    const cardWidth = 400;
    const cardHeight = 400;
    let left = rect.left + rect.width / 2 - cardWidth / 2;
    let top = rect.bottom + 10;
    left = Math.max(10, Math.min(left, window.innerWidth - cardWidth - 10));
    if (top + cardHeight > window.innerHeight) {
      top = rect.top - cardHeight - 10;
    }
    card.style.left = `${left}px`;
    card.style.top = `${top}px`;
    const header = card.createDiv("marginalia-floating-card-header");
    header.createEl("h4", { text: "\u6279\u6CE8" });
    const closeBtn = header.createEl("button", { cls: "marginalia-floating-card-close" });
    closeBtn.textContent = "\xD7";
    closeBtn.onclick = () => this.closeFloatingCard();
    const sourceEl = card.createDiv("marginalia-floating-card-source");
    sourceEl.createEl("blockquote", { text: annotation.selected_text });
    const contentEl = card.createDiv("marginalia-floating-card-content");
    const textarea = contentEl.createEl("textarea");
    textarea.value = annotation.content;
    textarea.placeholder = "\u8F93\u5165\u6279\u6CE8\u5185\u5BB9...";
    textarea.onblur = async () => {
      var _a2;
      const newContent = textarea.value;
      if (newContent !== annotation.content) {
        const updatedAnnotation = updateAnnotation(annotation, newContent);
        await updateAnnotation2(
          this.app.vault,
          this.activeFile,
          this.settings.annotationFolder,
          updatedAnnotation
        );
        const index = annotations.findIndex((a) => a.annotation_id === annotationId);
        if (index !== -1) {
          annotations[index] = updatedAnnotation;
        }
        (_a2 = this.sidebarView) == null ? void 0 : _a2.refresh();
      }
    };
    const footer = card.createDiv("marginalia-floating-card-footer");
    const deleteBtn = footer.createEl("button", {
      cls: "marginalia-btn marginalia-btn-danger marginalia-btn-icon",
      attr: { title: "\u5220\u9664\u6279\u6CE8" }
    });
    deleteBtn.innerHTML = "\u{1F5D1}\uFE0F";
    deleteBtn.onclick = () => {
      this.closeFloatingCard();
      this.handleAnnotationDelete(annotationId);
    };
    document.body.appendChild(card);
    this.floatingCard = card;
    textarea.focus();
    (_a = this.sidebarView) == null ? void 0 : _a.highlightAnnotationCard(annotationId);
    setTimeout(() => {
      const closeHandler = (e) => {
        if (!card.contains(e.target)) {
          this.closeFloatingCard();
          document.removeEventListener("click", closeHandler);
        }
      };
      document.addEventListener("click", closeHandler);
    }, 100);
  }
  /**
   * 关闭悬浮卡片
   */
  closeFloatingCard() {
    if (this.floatingCard) {
      this.floatingCard.remove();
      this.floatingCard = null;
      this.currentEditAnnotationId = null;
    }
  }
  /**
   * 处理侧边栏批注卡片点击
   */
  async handleAnnotationClick(annotation) {
    console.log(`[Marginalia] Sidebar card clicked: ${annotation.annotation_id}`);
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!markdownView) {
      console.warn("[Marginalia] No markdown view found");
      return;
    }
    if (markdownView.getMode() !== "preview") {
      console.warn("[Marginalia] Not in preview mode, cannot activate highlight");
      return;
    }
    await this.activateHighlightInDocument(annotation.annotation_id);
  }
  /**
   * 处理批注编辑（来自侧边栏）
   */
  async handleAnnotationEdit(annotation, content) {
    if (!this.activeFile)
      return;
    const updatedAnnotation = updateAnnotation(annotation, content);
    await updateAnnotation2(
      this.app.vault,
      this.activeFile,
      this.settings.annotationFolder,
      updatedAnnotation
    );
    const annotations = this.annotationCache.get(this.activeFile.path) || [];
    const index = annotations.findIndex((a) => a.annotation_id === annotation.annotation_id);
    if (index !== -1) {
      annotations[index] = updatedAnnotation;
    }
  }
  /**
   * 处理批注删除
   */
  async handleAnnotationDelete(annotationId) {
    var _a;
    if (!this.activeFile)
      return;
    await deleteAnnotation(
      this.app.vault,
      this.activeFile,
      this.settings.annotationFolder,
      annotationId
    );
    const annotations = this.annotationCache.get(this.activeFile.path) || [];
    const filtered = annotations.filter((a) => a.annotation_id !== annotationId);
    this.annotationCache.set(this.activeFile.path, filtered);
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (markdownView && markdownView.getMode() === "preview") {
      const possibleSelectors = [
        ".markdown-preview-view",
        ".markdown-reading-view",
        ".view-content",
        ".markdown-rendered"
      ];
      for (const selector of possibleSelectors) {
        const containers = markdownView.containerEl.querySelectorAll(selector);
        containers.forEach((container) => {
          if (container instanceof HTMLElement) {
            const highlight = container.querySelector(`[data-annotation-id="${annotationId}"]`);
            if (highlight && highlight.parentNode) {
              const parent = highlight.parentNode;
              while (highlight.firstChild) {
                parent.insertBefore(highlight.firstChild, highlight);
              }
              parent.removeChild(highlight);
              parent.normalize();
              console.log(`[Marginalia] Removed highlight ${annotationId} from ${selector}`);
            }
          }
        });
      }
    }
    await ((_a = this.sidebarView) == null ? void 0 : _a.refresh());
  }
  /**
   * 处理跳转到源文本
   */
  async handleGotoSource(annotation) {
    await this.activateHighlightInDocument(annotation.annotation_id);
  }
  /**
   * 处理跳转到批注文件
   */
  async handleGotoAnnotationFile(annotation) {
    if (!this.activeFile)
      return;
    const annotationFile = getAnnotationFile(
      this.app.vault,
      this.activeFile,
      this.settings.annotationFolder
    );
    if (annotationFile) {
      await this.app.workspace.openLinkText(
        annotationFile.path,
        "",
        false
      );
    }
  }
};
var AnnotationInputModal = class extends import_obsidian3.Modal {
  constructor(app, selectedText, onSubmit) {
    super(app);
    this.content = "";
    this.selectedText = selectedText;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("marginalia-input-modal-compact");
    const header = contentEl.createDiv("marginalia-input-modal-header");
    header.createEl("h4", { text: "\u6DFB\u52A0\u6279\u6CE8" });
    const sourceEl = contentEl.createDiv("marginalia-input-modal-source-compact");
    sourceEl.createEl("p", { text: this.selectedText });
    const textarea = contentEl.createEl("textarea");
    textarea.className = "marginalia-input-modal-textarea";
    textarea.placeholder = "\u8F93\u5165\u6279\u6CE8\u5185\u5BB9...";
    textarea.value = this.content;
    textarea.oninput = () => {
      this.content = textarea.value;
    };
    const actionsEl = contentEl.createDiv("marginalia-input-modal-actions-compact");
    const cancelBtn = actionsEl.createEl("button", {
      cls: "marginalia-btn-compact marginalia-btn-secondary",
      text: "\u53D6\u6D88"
    });
    cancelBtn.onclick = () => this.close();
    const saveBtn = actionsEl.createEl("button", {
      cls: "marginalia-btn-compact",
      text: "\u4FDD\u5B58"
    });
    saveBtn.onclick = () => {
      this.onSubmit(this.content);
      this.close();
    };
    setTimeout(() => textarea.focus(), 100);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var MarginaliaSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian \u6279\u6CE8\u63D2\u4EF6\u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("\u6279\u6CE8\u6587\u4EF6\u5939").setDesc("\u6279\u6CE8\u6587\u4EF6\u5B58\u50A8\u7684\u6587\u4EF6\u5939\u4F4D\u7F6E").addText(
      (text) => text.setPlaceholder("_annotations").setValue(this.plugin.settings.annotationFolder).onChange(async (value) => {
        this.plugin.settings.annotationFolder = value || "_annotations";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u81EA\u52A8\u663E\u793A\u4FA7\u8FB9\u680F").setDesc("\u6253\u5F00\u6709\u6279\u6CE8\u7684\u6587\u4EF6\u65F6\u81EA\u52A8\u663E\u793A\u6279\u6CE8\u4FA7\u8FB9\u680F").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoShowSidebar).onChange(async (value) => {
        this.plugin.settings.autoShowSidebar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u9AD8\u4EAE\u989C\u8272").setDesc("\u6B63\u6587\u4E2D\u9AD8\u4EAE\u6587\u672C\u7684\u80CC\u666F\u989C\u8272").addColorPicker(
      (picker) => picker.setValue(this.plugin.settings.highlightColor).onChange(async (value) => {
        this.plugin.settings.highlightColor = value;
        await this.plugin.saveSettings();
        this.refreshHighlights();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u5728\u79FB\u52A8\u7AEF\u542F\u7528").setDesc("\u5728\u79FB\u52A8\u8BBE\u5907\u4E0A\u542F\u7528\u6279\u6CE8\u529F\u80FD").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.mobileEnabled).onChange(async (value) => {
        this.plugin.settings.mobileEnabled = value;
        await this.plugin.saveSettings();
      })
    );
  }
  refreshHighlights() {
    var _a;
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (markdownView) {
      const preview = (_a = markdownView.previewMode) == null ? void 0 : _a.containerEl;
      if (preview) {
        updateHighlightColor(preview, this.plugin.settings.highlightColor);
      }
    }
  }
};
