/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnnotationPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var ANNOTATION_PREVIEW_VIEW_TYPE = "annotation-preview-view";
var annotationsUpdatedEffect = import_state.StateEffect.define();
var DEFAULT_SETTINGS = {
  annotationFolder: "Annotations",
  showAnnotationPreview: true,
  previewPosition: "right",
  highlightColor: "#ffeb3b"
};
var AnnotationPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.annotations = /* @__PURE__ */ new Map();
    this.highlightPlugin = null;
    this.activeTooltip = null;
    this.isMobile = false;
    this.touchStartTime = 0;
    this.touchStartPos = { x: 0, y: 0 };
  }
  async onload() {
    console.log("\u52A0\u8F7D\u6279\u6CE8\u63D2\u4EF6");
    this.isMobile = this.detectMobile();
    if (this.isMobile) {
      console.log("\u68C0\u6D4B\u5230\u79FB\u52A8\u7AEF\u8BBE\u5907");
      document.body.classList.add("annotation-mobile");
    }
    await this.loadSettings();
    this.registerHighlightPlugin();
    this.addSettingTab(new AnnotationSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(async () => {
      console.log("Workspace layout ready, \u5F00\u59CB\u52A0\u8F7D\u6279\u6CE8\u6570\u636E");
      await this.loadAnnotations();
      this.refreshHighlights();
      const activeFile = this.getActiveFile();
      if (activeFile && !this.isMobile) {
        this.updateAnnotationPanel();
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", this.handleEditorMenu.bind(this))
    );
    this.registerEvent(
      this.app.workspace.on("editor-change", this.handleEditorChange.bind(this))
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file) {
          setTimeout(() => {
            this.refreshHighlights();
            if (!this.isMobile) {
              this.updateAnnotationPanel();
            }
          }, 100);
        }
      })
    );
    if (this.isMobile) {
      this.registerMobileEvents();
    } else {
      this.registerDomEvent(document, "click", (evt) => {
        this.handleEditorClick(evt);
      });
      this.registerDomEvent(document, "dblclick", (evt) => {
        const target = evt.target;
        if (target.classList.contains("annotation-highlight") || target.closest(".annotation-highlight")) {
          evt.preventDefault();
          evt.stopPropagation();
          const highlightEl = target.classList.contains("annotation-highlight") ? target : target.closest(".annotation-highlight");
          const annotationId = highlightEl.getAttribute("data-annotation-id");
          if (annotationId) {
            this.showAnnotationTooltip(highlightEl, annotationId);
          }
        }
      });
      this.registerDomEvent(document, "click", (evt) => {
        const target = evt.target;
        if (!target.closest(".annotation-tooltip") && this.activeTooltip) {
          this.hideAnnotationTooltip();
        }
      });
      this.registerDomEvent(document, "keydown", (evt) => {
        if (evt.ctrlKey || evt.metaKey) {
          document.body.classList.add("ctrl-pressed");
        }
      });
      this.registerDomEvent(document, "keyup", (evt) => {
        if (!evt.ctrlKey && !evt.metaKey) {
          document.body.classList.remove("ctrl-pressed");
        }
      });
    }
    this.addCommand({
      id: "add-annotation",
      name: "\u6DFB\u52A0\u6279\u6CE8",
      editorCallback: (editor, view) => {
        this.addAnnotation(editor, view);
      }
    });
    this.addCommand({
      id: "toggle-annotation-preview",
      name: "\u5207\u6362\u6279\u6CE8\u9884\u89C8\u9762\u677F",
      callback: () => {
        this.toggleAnnotationPreview();
      }
    });
    this.addCommand({
      id: "toggle-annotation-sidebar",
      name: "\u5207\u6362\u4FA7\u8FB9\u6279\u6CE8\u663E\u793A",
      callback: () => {
        this.toggleAnnotationSidebar();
      }
    });
    this.addStyles();
    this.registerView(
      ANNOTATION_PREVIEW_VIEW_TYPE,
      (leaf) => new AnnotationPreviewView(leaf, this)
    );
    this.addRibbonIcon("quote-glyph", "\u6279\u6CE8", (evt) => {
      this.toggleAnnotationPreview();
    });
    if (this.settings.showAnnotationPreview) {
      this.app.workspace.onLayoutReady(() => {
        this.activateAnnotationPreview();
      });
    }
  }
  onunload() {
    console.log("\u5378\u8F7D\u6279\u6CE8\u63D2\u4EF6");
    this.removeStyles();
  }
  // 处理编辑器右键菜单
  handleEditorMenu(menu, editor, view) {
    const selection = editor.getSelection();
    if (selection && selection.trim().length > 0) {
      menu.addItem((item) => {
        item.setTitle("\u6DFB\u52A0\u6279\u6CE8").setIcon("quote-glyph").onClick(() => {
          this.addAnnotation(editor, view);
        });
      });
    }
  }
  // 处理编辑器变化
  handleEditorChange(editor, view) {
    this.updateHighlights(view);
  }
  // 添加批注
  async addAnnotation(editor, view) {
    var _a;
    const selection = editor.getSelection();
    if (!selection || selection.trim().length === 0) {
      new import_obsidian.Notice("\u8BF7\u5148\u9009\u62E9\u8981\u6279\u6CE8\u7684\u6587\u5B57");
      return;
    }
    const from = editor.getCursor("from");
    const to = editor.getCursor("to");
    const startOffset = editor.posToOffset(from);
    const endOffset = editor.posToOffset(to);
    const sourceFile = (_a = view.file) == null ? void 0 : _a.path;
    if (!sourceFile) {
      new import_obsidian.Notice("\u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u6587\u4EF6\u8DEF\u5F84");
      return;
    }
    this.hideAnnotationTooltip();
    setTimeout(() => {
      new AnnotationModal(this.app, selection, async (content) => {
        const annotation = {
          id: this.generateId(),
          sourceFile,
          startOffset,
          endOffset,
          selectedText: selection,
          content,
          createdAt: Date.now(),
          updatedAt: Date.now()
        };
        await this.saveAnnotation(annotation);
        setTimeout(() => {
          this.forceRefreshHighlights();
        }, 50);
        await this.updateAnnotationPanel();
        new import_obsidian.Notice("\u6279\u6CE8\u5DF2\u4FDD\u5B58");
      }).open();
    }, 50);
  }
  // 保存批注
  async saveAnnotation(annotation) {
    await this.ensureAnnotationFolder();
    const annotationFilePath = this.getAnnotationFilePath(annotation.sourceFile);
    let existingAnnotations = [];
    let fileExists = false;
    try {
      const file = this.app.vault.getAbstractFileByPath(annotationFilePath);
      if (file instanceof import_obsidian.TFile) {
        try {
          const content = await this.app.vault.read(file);
          existingAnnotations = this.parseAnnotationFile(content) || [];
          fileExists = true;
        } catch (readError) {
          fileExists = false;
          existingAnnotations = [];
        }
      }
    } catch (e) {
      fileExists = false;
    }
    existingAnnotations.push(annotation);
    const fileContent = this.formatAnnotationFile(existingAnnotations, annotation.sourceFile);
    try {
      if (fileExists) {
        const file = this.app.vault.getAbstractFileByPath(annotationFilePath);
        if (file instanceof import_obsidian.TFile) {
          await this.app.vault.modify(file, fileContent);
        } else {
          await this.app.vault.create(annotationFilePath, fileContent);
        }
      } else {
        await this.app.vault.create(annotationFilePath, fileContent);
      }
    } catch (writeError) {
      console.error("\u4FDD\u5B58\u6279\u6CE8\u6587\u4EF6\u5931\u8D25:", writeError);
      throw new Error("\u4FDD\u5B58\u6279\u6CE8\u5931\u8D25: " + writeError.message);
    }
    this.annotations.set(annotation.sourceFile, existingAnnotations);
  }
  // 加载批注
  async loadAnnotations() {
    this.annotations.clear();
    const folder = this.app.vault.getAbstractFileByPath(this.settings.annotationFolder);
    if (folder instanceof import_obsidian.TFolder) {
      for (const file of folder.children) {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          try {
            const content = await this.app.vault.read(file);
            const annotations = this.parseAnnotationFile(content);
            if (annotations.length > 0) {
              const sourceFile = annotations[0].sourceFile;
              this.annotations.set(sourceFile, annotations);
            }
          } catch (e) {
            console.error("\u52A0\u8F7D\u6279\u6CE8\u6587\u4EF6\u5931\u8D25:", file.path, e);
          }
        }
      }
    }
  }
  // 解析批注文件
  parseAnnotationFile(content) {
    const annotations = [];
    const lines = content.split("\n");
    let currentAnnotation = {};
    let inFrontMatter = false;
    let contentLines = [];
    let foundFirstAnnotation = false;
    for (const line of lines) {
      if (line === "---") {
        if (!inFrontMatter) {
          inFrontMatter = true;
          if (Object.keys(currentAnnotation).length > 0) {
            currentAnnotation.content = contentLines.join("\n").trim();
            annotations.push(currentAnnotation);
            currentAnnotation = {};
            contentLines = [];
          }
        } else {
          inFrontMatter = false;
          foundFirstAnnotation = true;
        }
        continue;
      }
      if (inFrontMatter) {
        const match = line.match(/^(.+?):\s*(.+)$/);
        if (match) {
          const key = match[1].trim();
          const value = match[2].trim();
          switch (key) {
            case "id":
              currentAnnotation.id = value;
              break;
            case "sourceFile":
              currentAnnotation.sourceFile = value;
              break;
            case "startOffset":
              currentAnnotation.startOffset = parseInt(value);
              break;
            case "endOffset":
              currentAnnotation.endOffset = parseInt(value);
              break;
            case "selectedText":
              currentAnnotation.selectedText = value;
              break;
            case "createdAt":
              currentAnnotation.createdAt = parseInt(value);
              break;
            case "updatedAt":
              currentAnnotation.updatedAt = parseInt(value);
              break;
          }
        }
      } else if (line.trim() !== "" && foundFirstAnnotation) {
        contentLines.push(line);
      }
    }
    if (Object.keys(currentAnnotation).length > 0) {
      currentAnnotation.content = contentLines.join("\n").trim();
      annotations.push(currentAnnotation);
    }
    return annotations;
  }
  // 更新批注内容
  async updateAnnotation(annotation) {
    const annotationFilePath = this.getAnnotationFilePath(annotation.sourceFile);
    const file = this.app.vault.getAbstractFileByPath(annotationFilePath);
    if (!(file instanceof import_obsidian.TFile)) {
      throw new Error("\u6279\u6CE8\u6587\u4EF6\u4E0D\u5B58\u5728");
    }
    const content = await this.app.vault.read(file);
    const annotations = this.parseAnnotationFile(content);
    const index = annotations.findIndex((a) => a.id === annotation.id);
    if (index === -1) {
      throw new Error("\u6279\u6CE8\u4E0D\u5B58\u5728");
    }
    annotation.updatedAt = Date.now();
    annotations[index] = annotation;
    const fileContent = this.formatAnnotationFile(annotations, annotation.sourceFile);
    await this.app.vault.modify(file, fileContent);
    this.annotations.set(annotation.sourceFile, annotations);
  }
  // 删除批注
  async deleteAnnotation(annotationId, sourceFile) {
    const annotationFilePath = this.getAnnotationFilePath(sourceFile);
    const file = this.app.vault.getAbstractFileByPath(annotationFilePath);
    if (!(file instanceof import_obsidian.TFile)) {
      throw new Error("\u6279\u6CE8\u6587\u4EF6\u4E0D\u5B58\u5728");
    }
    const content = await this.app.vault.read(file);
    let annotations = this.parseAnnotationFile(content);
    annotations = annotations.filter((a) => a.id !== annotationId);
    const fileContent = this.formatAnnotationFile(annotations, sourceFile);
    await this.app.vault.modify(file, fileContent);
    if (annotations.length === 0) {
      this.annotations.delete(sourceFile);
    } else {
      this.annotations.set(sourceFile, annotations);
    }
  }
  // 格式化批注文件
  formatAnnotationFile(annotations, sourceFile) {
    let content = `# \u6279\u6CE8: ${sourceFile}

`;
    content += `> \u6E90\u6587\u4EF6: [[${sourceFile}]]

`;
    for (const annotation of annotations) {
      content += `---
`;
      content += `id: ${annotation.id}
`;
      content += `sourceFile: ${annotation.sourceFile}
`;
      content += `startOffset: ${annotation.startOffset}
`;
      content += `endOffset: ${annotation.endOffset}
`;
      content += `selectedText: ${annotation.selectedText.replace(/\n/g, " ")}
`;
      content += `createdAt: ${annotation.createdAt}
`;
      content += `updatedAt: ${annotation.updatedAt}
`;
      content += `---

`;
      content += `${annotation.content}

`;
    }
    return content;
  }
  // 获取批注文件路径
  getAnnotationFilePath(sourceFile) {
    const lastSlash = sourceFile.lastIndexOf("/");
    const lastBackslash = sourceFile.lastIndexOf("\\");
    const separator = Math.max(lastSlash, lastBackslash);
    let fileName = sourceFile;
    if (separator >= 0) {
      fileName = sourceFile.substring(separator + 1);
    }
    const lastDot = fileName.lastIndexOf(".");
    if (lastDot > 0) {
      fileName = fileName.substring(0, lastDot);
    }
    return `${this.settings.annotationFolder}/${fileName}-annotation.md`;
  }
  // 确保批注文件夹存在
  async ensureAnnotationFolder() {
    var _a;
    try {
      const folder = this.app.vault.getAbstractFileByPath(this.settings.annotationFolder);
      if (!folder) {
        await this.app.vault.createFolder(this.settings.annotationFolder);
      }
    } catch (error) {
      if (!((_a = error.message) == null ? void 0 : _a.includes("already exists"))) {
        throw error;
      }
    }
  }
  // 注册高亮插件
  registerHighlightPlugin() {
    const plugin = this;
    const annotationsField = import_state.StateField.define({
      create() {
        return 0;
      },
      update(value, tr) {
        for (const effect of tr.effects) {
          if (effect.is(annotationsUpdatedEffect)) {
            return value + 1;
          }
        }
        return value;
      }
    });
    this.highlightPlugin = import_view.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.lastUpdateCount = 0;
          this.decorations = plugin.buildDecorations(view);
        }
        update(update) {
          const currentCount = update.state.field(annotationsField);
          if (update.docChanged || update.viewportChanged || currentCount !== this.lastUpdateCount) {
            this.decorations = plugin.buildDecorations(update.view);
            this.lastUpdateCount = currentCount;
          }
        }
      },
      {
        decorations: (v) => v.decorations
      }
    );
    this.registerEditorExtension([annotationsField, this.highlightPlugin]);
  }
  // 构建装饰器
  buildDecorations(view) {
    const builder = new import_state.RangeSetBuilder();
    const activeFile = this.getActiveFile();
    if (!activeFile) {
      return builder.finish();
    }
    const annotations = this.annotations.get(activeFile) || [];
    for (const annotation of annotations) {
      if (annotation.startOffset < view.state.doc.length && annotation.endOffset <= view.state.doc.length) {
        const from = annotation.startOffset;
        const to = annotation.endOffset;
        const decoration = import_view.Decoration.mark({
          class: "annotation-highlight",
          attributes: {
            "data-annotation-id": annotation.id
          }
        });
        builder.add(from, to, decoration);
      }
    }
    return builder.finish();
  }
  // 获取当前活动文件路径
  getActiveFile() {
    var _a;
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    return ((_a = activeView == null ? void 0 : activeView.file) == null ? void 0 : _a.path) || null;
  }
  // 刷新高亮
  refreshHighlights() {
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && view.editor) {
        this.updateHighlights(view);
      }
    }
    if (leaves.length === 0) {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView && activeView.editor) {
        this.updateHighlights(activeView);
      }
    }
  }
  // 更新高亮显示
  updateHighlights(view) {
    const file = view.file;
    if (!file)
      return;
    const annotations = this.annotations.get(file.path) || [];
    const editorView = view.editor.cm;
    if (editorView) {
      editorView.dispatch({
        effects: []
        // 空效果也会触发重新渲染
      });
    }
  }
  // 强制完全刷新所有高亮（用于新增/编辑批注后）
  forceRefreshHighlights() {
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && view.file && view.editor) {
        const editorView = view.editor.cm;
        if (editorView) {
          editorView.dispatch({
            effects: annotationsUpdatedEffect.of()
          });
        }
      }
    }
    if (leaves.length === 0) {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView && activeView.editor) {
        const editorView = activeView.editor.cm;
        if (editorView) {
          editorView.dispatch({
            effects: annotationsUpdatedEffect.of()
          });
        }
      }
    }
  }
  // 高亮正文中指定的批注
  highlightAnnotationInEditor(annotationId) {
    document.querySelectorAll(".annotation-highlight-active").forEach((el) => {
      el.classList.remove("annotation-highlight-active");
    });
    document.querySelectorAll(`.annotation-highlight[data-annotation-id="${annotationId}"]`).forEach((el) => {
      el.classList.add("annotation-highlight-active");
    });
  }
  // 处理编辑器点击事件
  handleEditorClick(evt) {
    const target = evt.target;
    if (target.classList.contains("annotation-highlight") || target.closest(".annotation-highlight")) {
      evt.preventDefault();
      evt.stopPropagation();
      const highlightEl = target.classList.contains("annotation-highlight") ? target : target.closest(".annotation-highlight");
      const annotationId = highlightEl.getAttribute("data-annotation-id");
      if (!annotationId)
        return;
      if (evt.ctrlKey || evt.metaKey) {
        this.openAnnotationFileAtAnnotation(annotationId);
      } else {
        this.highlightAnnotationInSidebar(annotationId);
      }
    } else if (this.activeTooltip) {
      this.hideAnnotationTooltip();
    }
  }
  // 高亮右侧功能栏的对应批注记录
  highlightAnnotationInSidebar(annotationId) {
    const { workspace } = this.app;
    const leaves = workspace.getLeavesOfType(ANNOTATION_PREVIEW_VIEW_TYPE);
    if (leaves.length === 0) {
      this.activateAnnotationPreview();
      setTimeout(() => {
        this.highlightAnnotationInSidebar(annotationId);
      }, 300);
      return;
    }
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && view.contentEl) {
        view.contentEl.querySelectorAll(".annotation-sidebar-item").forEach((el) => {
          el.classList.remove("active");
        });
        const item = view.contentEl.querySelector(`[data-annotation-id="${annotationId}"]`);
        if (item) {
          item.classList.add("active");
          item.scrollIntoView({ behavior: "smooth", block: "center" });
        }
      }
    }
  }
  // 打开批注文件并定位到具体批注位置（Ctrl+点击使用）
  async openAnnotationFileAtAnnotation(annotationId) {
    const activeFile = this.getActiveFile();
    if (!activeFile)
      return;
    const annotationFilePath = this.getAnnotationFilePath(activeFile);
    const annotationFile = this.app.vault.getAbstractFileByPath(annotationFilePath);
    if (annotationFile instanceof import_obsidian.TFile) {
      const content = await this.app.vault.read(annotationFile);
      const regex = new RegExp(`^id:\\s*${annotationId}$`, "m");
      const match = content.match(regex);
      if (match && match.index !== void 0) {
        const linesBefore = content.substring(0, match.index).split("\n").length;
        await this.app.workspace.openLinkText(annotationFilePath, "", false);
        setTimeout(() => {
          const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
          if (activeView && activeView.editor) {
            const pos = { line: linesBefore - 1, ch: 0 };
            activeView.editor.setCursor(pos);
            activeView.editor.scrollIntoView({ from: pos, to: pos }, true);
          }
        }, 200);
      } else {
        await this.app.workspace.openLinkText(annotationFilePath, "", false);
      }
    } else {
      new import_obsidian.Notice("\u6279\u6CE8\u6587\u4EF6\u4E0D\u5B58\u5728");
    }
  }
  // 显示批注悬浮提示（双击显示，支持滚动和编辑）
  showAnnotationTooltip(element, annotationId) {
    this.hideAnnotationTooltip();
    const activeFile = this.getActiveFile();
    if (!activeFile)
      return;
    const annotations = this.annotations.get(activeFile) || [];
    const annotation = annotations.find((a) => a.id === annotationId);
    if (!annotation)
      return;
    const tooltip = document.createElement("div");
    tooltip.className = "annotation-tooltip";
    tooltip.setAttribute("data-annotation-id", annotationId);
    const closeBtn = tooltip.createEl("button", {
      cls: "annotation-tooltip-close",
      text: "\xD7"
    });
    closeBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.hideAnnotationTooltip();
    });
    const contentContainer = tooltip.createEl("div", {
      cls: "annotation-tooltip-content-container"
    });
    const contentEl = contentContainer.createEl("div", {
      cls: "annotation-tooltip-content markdown-rendered"
    });
    import_obsidian.MarkdownRenderer.render(
      this.app,
      annotation.content,
      contentEl,
      annotation.sourceFile,
      this
    ).then(() => {
      this.setupImageHoverPreview(contentEl);
    });
    const footerEl = tooltip.createEl("div", {
      cls: "annotation-tooltip-footer"
    });
    const date = new Date(annotation.createdAt);
    const dateStr = `${date.getFullYear().toString().slice(-2)}-${(date.getMonth() + 1).toString().padStart(2, "0")}-${date.getDate().toString().padStart(2, "0")} ${date.getHours().toString().padStart(2, "0")}:${date.getMinutes().toString().padStart(2, "0")}`;
    footerEl.createEl("span", {
      cls: "annotation-tooltip-date",
      text: dateStr
    });
    const btnGroup = footerEl.createEl("div", {
      cls: "annotation-tooltip-btn-group"
    });
    const editBtn = btnGroup.createEl("button", {
      cls: "annotation-tooltip-btn",
      attr: { "aria-label": "\u7F16\u8F91\u6279\u6CE8" }
    });
    editBtn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>';
    editBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.enableInlineEdit(tooltip, annotation, contentEl, contentContainer);
    });
    const deleteBtn = btnGroup.createEl("button", {
      cls: "annotation-tooltip-btn annotation-tooltip-btn-delete",
      attr: { "aria-label": "\u5220\u9664\u6279\u6CE8" }
    });
    deleteBtn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/></svg>';
    deleteBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      if (this.activeTooltip) {
        const tooltipToRemove = this.activeTooltip;
        this.activeTooltip = null;
        tooltipToRemove.remove();
      }
      try {
        await this.deleteAnnotation(annotation.id, annotation.sourceFile);
        this.updateAnnotationPanel();
        this.forceRefreshHighlights();
        new import_obsidian.Notice("\u6279\u6CE8\u5DF2\u5220\u9664");
      } catch (error) {
        console.error("\u5220\u9664\u6279\u6CE8\u5931\u8D25:", error);
        new import_obsidian.Notice("\u5220\u9664\u6279\u6CE8\u5931\u8D25");
      }
    });
    if (this.isMobile) {
      tooltip.style.position = "fixed";
      tooltip.style.left = "50%";
      tooltip.style.transform = "translateX(-50%)";
      tooltip.style.bottom = "20px";
      tooltip.style.top = "auto";
      tooltip.style.maxWidth = "90vw";
      tooltip.style.width = "90vw";
      tooltip.style.maxHeight = "60vh";
    } else {
      const rect = element.getBoundingClientRect();
      tooltip.style.left = `${rect.left}px`;
      tooltip.style.top = `${rect.bottom + 5}px`;
      if (rect.left + 300 > window.innerWidth) {
        tooltip.style.left = `${window.innerWidth - 320}px`;
      }
      if (rect.bottom + 250 > window.innerHeight) {
        tooltip.style.top = `${rect.top - 260}px`;
      }
    }
    document.body.appendChild(tooltip);
    this.activeTooltip = tooltip;
  }
  // 隐藏批注悬浮提示
  hideAnnotationTooltip() {
    if (this.activeTooltip) {
      this.activeTooltip.remove();
      this.activeTooltip = null;
    }
  }
  // 启用行内编辑模式
  enableInlineEdit(tooltip, annotation, contentEl, contentContainer) {
    const originalContent = annotation.content;
    let isEditing = true;
    contentContainer.empty();
    const textarea = contentContainer.createEl("textarea", {
      cls: "annotation-inline-editor"
    });
    textarea.value = originalContent;
    textarea.style.cssText = `
			width: 100%;
			min-height: 100px;
			max-height: 200px;
			resize: vertical;
			border: 1px solid var(--background-modifier-border);
			border-radius: 4px;
			padding: 8px;
			background: var(--background-primary);
			color: var(--text-normal);
			font-size: 14px;
			line-height: 1.5;
		`;
    textarea.focus();
    textarea.setSelectionRange(textarea.value.length, textarea.value.length);
    const stopPropagation = (e) => {
      e.stopPropagation();
    };
    textarea.addEventListener("click", stopPropagation);
    textarea.addEventListener("mousedown", stopPropagation);
    textarea.addEventListener("mouseup", stopPropagation);
    contentContainer.addEventListener("click", stopPropagation);
    const cancelEdit = () => {
      if (!isEditing)
        return;
      isEditing = false;
      textarea.removeEventListener("click", stopPropagation);
      textarea.removeEventListener("mousedown", stopPropagation);
      textarea.removeEventListener("mouseup", stopPropagation);
      contentContainer.removeEventListener("click", stopPropagation);
      contentContainer.empty();
      const newContentEl = contentContainer.createEl("div", {
        cls: "annotation-tooltip-content markdown-rendered"
      });
      import_obsidian.MarkdownRenderer.render(
        this.app,
        originalContent,
        newContentEl,
        annotation.sourceFile,
        this
      ).then(() => {
        this.setupImageHoverPreview(newContentEl);
      });
    };
    const saveEdit = async () => {
      if (!isEditing)
        return;
      isEditing = false;
      textarea.removeEventListener("click", stopPropagation);
      textarea.removeEventListener("mousedown", stopPropagation);
      textarea.removeEventListener("mouseup", stopPropagation);
      contentContainer.removeEventListener("click", stopPropagation);
      const newContent = textarea.value.trim();
      if (!newContent) {
        cancelEdit();
        return;
      }
      annotation.content = newContent;
      await this.updateAnnotation(annotation);
      contentContainer.empty();
      const newContentEl = contentContainer.createEl("div", {
        cls: "annotation-tooltip-content markdown-rendered"
      });
      import_obsidian.MarkdownRenderer.render(
        this.app,
        newContent,
        newContentEl,
        annotation.sourceFile,
        this
      ).then(() => {
        this.setupImageHoverPreview(newContentEl);
      });
      this.updateAnnotationPanel();
      this.forceRefreshHighlights();
    };
    textarea.addEventListener("blur", () => {
      setTimeout(() => {
        if (isEditing) {
          saveEdit();
        }
      }, 200);
    });
    textarea.addEventListener("keydown", (e) => {
      if (e.key === "Escape") {
        e.preventDefault();
        cancelEdit();
      } else if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        saveEdit();
      }
    });
  }
  // 设置图片悬停预览功能
  setupImageHoverPreview(container) {
    const images = container.querySelectorAll("img");
    images.forEach((img) => {
      var _a;
      img.style.display = "none";
      const imgLink = document.createElement("span");
      imgLink.className = "annotation-image-link";
      imgLink.textContent = "\u{1F5BC}\uFE0F \u56FE\u7247";
      imgLink.style.cursor = "pointer";
      imgLink.style.color = "var(--text-accent)";
      imgLink.style.textDecoration = "underline";
      imgLink.style.margin = "0 4px";
      let previewEl = null;
      imgLink.addEventListener("mouseenter", (e) => {
        if (previewEl)
          return;
        previewEl = document.createElement("div");
        previewEl.className = "annotation-image-preview";
        previewEl.style.cssText = `
					position: fixed;
					background: var(--background-primary);
					border: 1px solid var(--background-modifier-border);
					border-radius: 6px;
					padding: 8px;
					z-index: 10000;
					box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
					max-width: 300px;
					max-height: 200px;
					overflow: hidden;
				`;
        const previewImg = document.createElement("img");
        previewImg.src = img.src;
        previewImg.style.cssText = `
					max-width: 100%;
					max-height: 180px;
					object-fit: contain;
					border-radius: 4px;
				`;
        previewEl.appendChild(previewImg);
        const rect = imgLink.getBoundingClientRect();
        previewEl.style.left = `${rect.left}px`;
        previewEl.style.top = `${rect.bottom + 5}px`;
        if (rect.left + 300 > window.innerWidth) {
          previewEl.style.left = `${window.innerWidth - 320}px`;
        }
        if (rect.bottom + 200 > window.innerHeight) {
          previewEl.style.top = `${rect.top - 210}px`;
        }
        document.body.appendChild(previewEl);
      });
      imgLink.addEventListener("mouseleave", () => {
        if (previewEl) {
          previewEl.remove();
          previewEl = null;
        }
      });
      (_a = img.parentNode) == null ? void 0 : _a.insertBefore(imgLink, img);
    });
  }
  // 检测是否为移动端设备
  detectMobile() {
    const isTouchDevice = "ontouchstart" in window || navigator.maxTouchPoints > 0;
    const isSmallScreen = window.innerWidth <= 768;
    const mobileRegex = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i;
    const isMobileUA = mobileRegex.test(navigator.userAgent);
    return isTouchDevice && isSmallScreen || isMobileUA;
  }
  // 注册移动端事件
  registerMobileEvents() {
    this.registerDomEvent(document, "touchend", (evt) => {
      const touch = evt.changedTouches[0];
      const target = document.elementFromPoint(touch.clientX, touch.clientY);
      if (target && (target.classList.contains("annotation-highlight") || target.closest(".annotation-highlight"))) {
        const now = Date.now();
        const timeDiff = now - this.touchStartTime;
        if (timeDiff < 300) {
          evt.preventDefault();
          evt.stopPropagation();
          const highlightEl = target.classList.contains("annotation-highlight") ? target : target.closest(".annotation-highlight");
          const annotationId = highlightEl.getAttribute("data-annotation-id");
          if (annotationId) {
            this.showAnnotationTooltip(highlightEl, annotationId);
          }
        }
        this.touchStartTime = now;
      }
    });
    this.registerDomEvent(document, "touchstart", (evt) => {
      const touch = evt.touches[0];
      this.touchStartPos = { x: touch.clientX, y: touch.clientY };
    });
    let longPressTimer = null;
    this.registerDomEvent(document, "touchstart", (evt) => {
      const touch = evt.touches[0];
      const target = document.elementFromPoint(touch.clientX, touch.clientY);
      if (target && (target.classList.contains("annotation-highlight") || target.closest(".annotation-highlight"))) {
        longPressTimer = window.setTimeout(() => {
          const highlightEl = target.classList.contains("annotation-highlight") ? target : target.closest(".annotation-highlight");
          const annotationId = highlightEl.getAttribute("data-annotation-id");
          if (annotationId) {
            this.showAnnotationTooltip(highlightEl, annotationId);
          }
        }, 500);
      }
    });
    this.registerDomEvent(document, "touchend", () => {
      if (longPressTimer) {
        clearTimeout(longPressTimer);
        longPressTimer = null;
      }
    });
    this.registerDomEvent(document, "touchmove", () => {
      if (longPressTimer) {
        clearTimeout(longPressTimer);
        longPressTimer = null;
      }
    });
    this.registerDomEvent(document, "touchstart", (evt) => {
      const touch = evt.touches[0];
      const target = document.elementFromPoint(touch.clientX, touch.clientY);
      if (this.activeTooltip && !(target == null ? void 0 : target.closest(".annotation-tooltip"))) {
        this.hideAnnotationTooltip();
      }
    });
  }
  // 切换批注预览面板（功能区样式）
  async toggleAnnotationPreview() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(ANNOTATION_PREVIEW_VIEW_TYPE);
    if (existing.length > 0) {
      workspace.detachLeavesOfType(ANNOTATION_PREVIEW_VIEW_TYPE);
    } else {
      await this.activateAnnotationPreview();
    }
  }
  // 激活批注预览面板 - 在右侧功能区显示
  async activateAnnotationPreview() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(ANNOTATION_PREVIEW_VIEW_TYPE);
    if (existing.length > 0) {
      for (const leaf2 of existing) {
        const view = leaf2.view;
        if (view && view.updatePreview) {
          view.currentFile = this.getActiveFile();
          view.updatePreview();
        }
      }
      return;
    }
    const leaf = workspace.getRightLeaf(false);
    if (!leaf) {
      console.error("\u65E0\u6CD5\u83B7\u53D6\u53F3\u4FA7\u8FB9\u680F");
      return;
    }
    await leaf.setViewState({
      type: ANNOTATION_PREVIEW_VIEW_TYPE,
      active: false
      // 不激活，保持当前焦点在编辑器
    });
  }
  // 更新批注面板（自动显示）- 避免重复创建
  async updateAnnotationPanel() {
    if (this.isMobile) {
      return;
    }
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(ANNOTATION_PREVIEW_VIEW_TYPE);
    if (existing.length > 0) {
      for (const leaf of existing) {
        const view = leaf.view;
        if (view && view.updatePreview) {
          view.currentFile = this.getActiveFile();
          view.updatePreview();
        }
      }
    } else if (this.settings.showAnnotationPreview) {
      await this.activateAnnotationPreview();
    }
  }
  // 切换侧边批注显示（Word式）
  async toggleAnnotationSidebar() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u4EF6");
      return;
    }
    const container = activeView.containerEl;
    let sidebar = container.querySelector(".annotation-word-sidebar");
    if (sidebar) {
      sidebar.remove();
      container.classList.remove("has-annotation-sidebar");
    } else {
      await this.createAnnotationSidebar(activeView);
    }
  }
  // 创建 Word 式侧边批注面板
  async createAnnotationSidebar(view) {
    const container = view.containerEl;
    const contentEl = container.querySelector(".view-content");
    if (!contentEl)
      return;
    container.classList.add("has-annotation-sidebar");
    const sidebar = document.createElement("div");
    sidebar.className = "annotation-word-sidebar";
    const header = sidebar.createEl("div", {
      cls: "annotation-word-sidebar-header",
      text: "\u6279\u6CE8"
    });
    const closeBtn = header.createEl("button", {
      cls: "annotation-word-sidebar-close",
      text: "\xD7"
    });
    closeBtn.addEventListener("click", () => {
      sidebar.remove();
      container.classList.remove("has-annotation-sidebar");
    });
    const content = sidebar.createEl("div", {
      cls: "annotation-word-sidebar-content"
    });
    const file = view.file;
    if (file) {
      const annotations = this.annotations.get(file.path) || [];
      if (annotations.length === 0) {
        content.createEl("div", {
          cls: "annotation-word-sidebar-empty",
          text: "\u6682\u65E0\u6279\u6CE8"
        });
      } else {
        const sortedAnnotations = [...annotations].sort((a, b) => a.startOffset - b.startOffset);
        for (const annotation of sortedAnnotations) {
          const item = content.createEl("div", {
            cls: "annotation-word-sidebar-item",
            attr: { "data-annotation-id": annotation.id }
          });
          const selectedText = annotation.selectedText.length > 40 ? annotation.selectedText.substring(0, 40) + "..." : annotation.selectedText;
          item.createEl("div", {
            cls: "annotation-word-sidebar-selected",
            text: `"${selectedText}"`
          });
          item.createEl("div", {
            cls: "annotation-word-sidebar-text",
            text: annotation.content
          });
          item.addEventListener("click", () => {
            const pos = view.editor.offsetToPos(annotation.startOffset);
            view.editor.setCursor(pos);
            view.editor.scrollIntoView({ from: pos, to: pos }, true);
            content.querySelectorAll(".annotation-word-sidebar-item").forEach((el) => {
              el.classList.remove("active");
            });
            item.classList.add("active");
          });
        }
      }
    }
    contentEl.appendChild(sidebar);
  }
  // 生成唯一ID
  generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
  }
  // 添加样式
  addStyles() {
    const style = document.createElement("style");
    style.id = "annotation-plugin-styles";
    style.textContent = `
			.annotation-highlight {
				background-color: var(--annotation-highlight-color, #ffeb3b);
				border-radius: 2px;
				padding: 0 2px;
				cursor: pointer;
			}
			.annotation-highlight:hover {
				background-color: var(--annotation-highlight-hover-color, #fdd835);
			}
			
			/* \u79FB\u52A8\u7AEF\u9002\u914D\u6837\u5F0F */
			.annotation-mobile .annotation-highlight {
				cursor: default;
			}
			
			/* \u79FB\u52A8\u7AEF tooltip \u6837\u5F0F\u4F18\u5316 */
			.annotation-mobile .annotation-tooltip {
				position: fixed;
				left: 50% !important;
				transform: translateX(-50%);
				max-width: 90vw;
				width: 90vw;
				max-height: 60vh;
			}
			
			/* \u79FB\u52A8\u7AEF\u884C\u5185\u7F16\u8F91\u5668\u4F18\u5316 */
			.annotation-mobile .annotation-inline-editor {
				font-size: 16px !important; /* \u9632\u6B62 iOS \u7F29\u653E */
				min-height: 120px;
			}
			
			/* \u79FB\u52A8\u7AEF\u4FA7\u8FB9\u680F\u9690\u85CF */
			.annotation-mobile .annotation-word-sidebar {
				display: none !important;
			}
			
			/* \u89E6\u6478\u53CD\u9988 */
			.annotation-mobile .annotation-highlight:active {
				background-color: var(--annotation-highlight-hover-color, #fdd835);
				opacity: 0.8;
			}
			
			/* \u79FB\u52A8\u7AEF\u64CD\u4F5C\u6309\u94AE\u4F18\u5316 */
			.annotation-mobile .annotation-tooltip-btn {
				min-width: 44px;
				min-height: 44px;
				font-size: 16px;
			}
			
			/* \u79FB\u52A8\u7AEF\u6309\u94AE\u5BB9\u5668\u4F18\u5316 */
			.annotation-mobile .annotation-inline-edit-buttons,
			.annotation-mobile .annotation-sidebar-inline-edit-buttons {
				padding: 8px 0;
			}
			
			.annotation-mobile .annotation-inline-btn,
			.annotation-mobile .annotation-sidebar-inline-btn {
				min-height: 36px;
				min-width: 60px;
				font-size: 14px;
			}
		`;
    document.head.appendChild(style);
  }
  // 移除样式
  removeStyles() {
    const style = document.getElementById("annotation-plugin-styles");
    if (style) {
      style.remove();
    }
  }
  // 加载设置
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  // 保存设置
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var AnnotationModal = class extends import_obsidian.Modal {
  constructor(app, selectedText, onSubmit) {
    super(app);
    this.content = "";
    this.selectedText = selectedText;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u6DFB\u52A0\u6279\u6CE8" });
    contentEl.createEl("p", {
      text: "\u9009\u4E2D\u5185\u5BB9:",
      cls: "annotation-selected-label"
    });
    const quoteEl = contentEl.createEl("blockquote", {
      text: this.selectedText.length > 100 ? this.selectedText.substring(0, 100) + "..." : this.selectedText,
      cls: "annotation-selected-text"
    });
    contentEl.createEl("p", {
      text: "\u6279\u6CE8\u5185\u5BB9:",
      cls: "annotation-content-label"
    });
    const textarea = contentEl.createEl("textarea", {
      cls: "annotation-textarea"
    });
    textarea.rows = 5;
    textarea.style.width = "100%";
    textarea.style.marginTop = "10px";
    textarea.placeholder = "\u5728\u6B64\u8F93\u5165\u60A8\u7684\u6279\u6CE8\u5185\u5BB9...";
    textarea.addEventListener("input", (e) => {
      this.content = e.target.value;
    });
    textarea.style.cssText = `
			width: 100%;
			min-height: 100px;
			resize: vertical;
			border: 1px solid var(--background-modifier-border);
			border-radius: 4px;
			padding: 10px;
			background: var(--background-primary);
			color: var(--text-normal);
			font-size: 14px;
			line-height: 1.5;
		`;
    const buttonContainer = contentEl.createEl("div", {
      cls: "annotation-button-container"
    });
    buttonContainer.style.marginTop = "20px";
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.justifyContent = "flex-end";
    const cancelButton = buttonContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelButton.addEventListener("click", () => {
      this.close();
    });
    const saveButton = buttonContainer.createEl("button", {
      text: "\u4FDD\u5B58",
      cls: "mod-cta"
    });
    saveButton.addEventListener("click", () => {
      if (this.content.trim()) {
        this.onSubmit(this.content);
        this.close();
      } else {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u6279\u6CE8\u5185\u5BB9");
      }
    });
    requestAnimationFrame(() => {
      setTimeout(() => {
        textarea.focus();
        textarea.setSelectionRange(textarea.value.length, textarea.value.length);
      }, 150);
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AnnotationPreviewView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentFile = null;
    this.plugin = plugin;
    this.navigation = false;
  }
  getViewType() {
    return ANNOTATION_PREVIEW_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u6279\u6CE8";
  }
  getIcon() {
    return "quote-glyph";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("annotation-right-sidebar-view");
    const header = container.createEl("div", {
      cls: "annotation-sidebar-header"
    });
    header.createEl("div", {
      cls: "annotation-sidebar-title",
      text: "\u6279\u6CE8"
    });
    header.createEl("div", {
      cls: "annotation-sidebar-count",
      text: "0 \u4E2A\u6279\u6CE8"
    });
    this.contentEl = container.createEl("div", {
      cls: "annotation-sidebar-content"
    });
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        this.currentFile = (file == null ? void 0 : file.path) || null;
        this.updatePreview();
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-change", () => {
        setTimeout(() => {
          this.updatePreview();
        }, 500);
      })
    );
    const activeFile = this.plugin.getActiveFile();
    this.currentFile = activeFile;
    this.updatePreview();
  }
  updatePreview() {
    this.contentEl.empty();
    const container = this.containerEl.children[1];
    const countEl = container.querySelector(".annotation-sidebar-count");
    if (!this.currentFile) {
      if (countEl)
        countEl.textContent = "0 \u4E2A\u6279\u6CE8";
      this.contentEl.createEl("div", {
        cls: "annotation-sidebar-empty",
        text: "\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u4EF6"
      });
      return;
    }
    const annotations = this.plugin.annotations.get(this.currentFile) || [];
    if (countEl) {
      countEl.textContent = `${annotations.length} \u4E2A\u6279\u6CE8`;
    }
    if (annotations.length === 0) {
      this.contentEl.createEl("div", {
        cls: "annotation-sidebar-empty",
        text: "\u5F53\u524D\u6587\u4EF6\u6CA1\u6709\u6279\u6CE8"
      });
      return;
    }
    const sortedAnnotations = [...annotations].sort((a, b) => a.startOffset - b.startOffset);
    for (const annotation of sortedAnnotations) {
      const item = this.contentEl.createEl("div", {
        cls: "annotation-sidebar-item",
        attr: { "data-annotation-id": annotation.id }
      });
      const selectedText = annotation.selectedText.length > 60 ? annotation.selectedText.substring(0, 60) + "..." : annotation.selectedText;
      item.createEl("div", {
        cls: "annotation-sidebar-quote",
        text: `"${selectedText}"`
      });
      const commentEl = item.createEl("div", {
        cls: "annotation-sidebar-comment markdown-rendered"
      });
      import_obsidian.MarkdownRenderer.render(
        this.app,
        annotation.content,
        commentEl,
        annotation.sourceFile,
        this.plugin
      ).then(() => {
        this.setupImageHoverPreview(commentEl);
      });
      const actions = item.createEl("div", {
        cls: "annotation-sidebar-actions"
      });
      const editBtn = actions.createEl("button", {
        cls: "annotation-sidebar-btn",
        attr: { "aria-label": "\u7F16\u8F91\u6279\u6CE8" }
      });
      editBtn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>';
      editBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.enableSidebarInlineEdit(annotation, commentEl, item);
      });
      const fileBtn = actions.createEl("button", {
        cls: "annotation-sidebar-btn",
        attr: { "aria-label": "\u6253\u5F00\u6279\u6CE8\u6587\u4EF6" }
      });
      fileBtn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14,2 14,8 20,8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>';
      fileBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.openAnnotationFile(annotation.id);
      });
      const deleteBtn = actions.createEl("button", {
        cls: "annotation-sidebar-btn annotation-sidebar-btn-delete",
        attr: { "aria-label": "\u5220\u9664\u6279\u6CE8" }
      });
      deleteBtn.innerHTML = '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/></svg>';
      deleteBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.deleteAnnotation(annotation);
      });
      const date = new Date(annotation.createdAt);
      const dateStr = `${date.getFullYear().toString().slice(-2)}-${(date.getMonth() + 1).toString().padStart(2, "0")}-${date.getDate().toString().padStart(2, "0")} ${date.getHours().toString().padStart(2, "0")}:${date.getMinutes().toString().padStart(2, "0")}`;
      const dateEl = item.createEl("div", {
        cls: "annotation-sidebar-date",
        text: dateStr
      });
      item.addEventListener("click", () => {
        this.jumpToAnnotation(annotation);
      });
    }
  }
  jumpToAnnotation(annotation) {
    const file = this.app.vault.getAbstractFileByPath(annotation.sourceFile);
    if (file instanceof import_obsidian.TFile) {
      this.contentEl.querySelectorAll(".annotation-sidebar-item").forEach((el) => {
        el.classList.remove("active");
      });
      const item = this.contentEl.querySelector(`[data-annotation-id="${annotation.id}"]`);
      if (item)
        item.classList.add("active");
      this.app.workspace.openLinkText(annotation.sourceFile, "", false, {
        active: true
      }).then(() => {
        setTimeout(() => {
          const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
          if (activeView && activeView.editor) {
            const pos = activeView.editor.offsetToPos(annotation.startOffset);
            activeView.editor.setCursor(pos);
            activeView.editor.scrollIntoView({ from: pos, to: pos }, true);
            this.plugin.highlightAnnotationInEditor(annotation.id);
          }
        }, 100);
      });
    }
  }
  async openAnnotationFile(annotationId) {
    if (!this.currentFile)
      return;
    const annotationFilePath = this.plugin.getAnnotationFilePath(this.currentFile);
    const annotationFile = this.app.vault.getAbstractFileByPath(annotationFilePath);
    if (annotationFile instanceof import_obsidian.TFile) {
      await this.app.workspace.openLinkText(annotationFilePath, "", false);
      setTimeout(() => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (!activeView || !activeView.editor)
          return;
        const content = activeView.editor.getValue();
        const regex = new RegExp(`^id:s*${annotationId}$`, "m");
        const match = content.match(regex);
        if (match && match.index !== void 0) {
          const pos = activeView.editor.offsetToPos(match.index);
          activeView.editor.setCursor(pos);
          activeView.editor.scrollIntoView({ from: pos, to: pos }, true);
        }
      }, 200);
    }
  }
  // 启用侧边栏行内编辑
  enableSidebarInlineEdit(annotation, commentEl, item) {
    const originalContent = annotation.content;
    let isEditing = true;
    commentEl.empty();
    commentEl.classList.remove("markdown-rendered");
    commentEl.classList.add("annotation-inline-edit-container");
    const textarea = commentEl.createEl("textarea", {
      cls: "annotation-sidebar-inline-editor"
    });
    textarea.value = originalContent;
    textarea.style.cssText = `
			width: 100%;
			min-height: 80px;
			max-height: 150px;
			resize: vertical;
			border: 1px solid var(--background-modifier-border);
			border-radius: 4px;
			padding: 6px;
			background: var(--background-primary);
			color: var(--text-normal);
			font-size: 13px;
			line-height: 1.4;
		`;
    textarea.focus();
    textarea.setSelectionRange(textarea.value.length, textarea.value.length);
    const stopPropagation = (e) => {
      e.stopPropagation();
    };
    textarea.addEventListener("click", stopPropagation);
    textarea.addEventListener("mousedown", stopPropagation);
    textarea.addEventListener("mouseup", stopPropagation);
    textarea.addEventListener("selectstart", stopPropagation);
    commentEl.addEventListener("click", stopPropagation);
    const cancelEdit = () => {
      if (!isEditing)
        return;
      isEditing = false;
      textarea.removeEventListener("click", stopPropagation);
      textarea.removeEventListener("mousedown", stopPropagation);
      textarea.removeEventListener("mouseup", stopPropagation);
      textarea.removeEventListener("selectstart", stopPropagation);
      commentEl.removeEventListener("click", stopPropagation);
      commentEl.empty();
      commentEl.classList.remove("annotation-inline-edit-container");
      commentEl.classList.add("markdown-rendered");
      import_obsidian.MarkdownRenderer.render(
        this.app,
        originalContent,
        commentEl,
        annotation.sourceFile,
        this.plugin
      ).then(() => {
        this.setupImageHoverPreview(commentEl);
      });
    };
    const saveEdit = async () => {
      if (!isEditing)
        return;
      isEditing = false;
      textarea.removeEventListener("click", stopPropagation);
      textarea.removeEventListener("mousedown", stopPropagation);
      textarea.removeEventListener("mouseup", stopPropagation);
      textarea.removeEventListener("selectstart", stopPropagation);
      commentEl.removeEventListener("click", stopPropagation);
      const newContent = textarea.value.trim();
      if (!newContent) {
        cancelEdit();
        return;
      }
      annotation.content = newContent;
      await this.plugin.updateAnnotation(annotation);
      commentEl.empty();
      commentEl.classList.remove("annotation-inline-edit-container");
      commentEl.classList.add("markdown-rendered");
      import_obsidian.MarkdownRenderer.render(
        this.app,
        newContent,
        commentEl,
        annotation.sourceFile,
        this.plugin
      ).then(() => {
        this.setupImageHoverPreview(commentEl);
      });
      this.plugin.forceRefreshHighlights();
    };
    textarea.addEventListener("blur", () => {
      setTimeout(() => {
        if (isEditing) {
          saveEdit();
        }
      }, 200);
    });
    textarea.addEventListener("keydown", (e) => {
      if (e.key === "Escape") {
        e.preventDefault();
        cancelEdit();
      } else if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        saveEdit();
      }
    });
  }
  async editAnnotation(annotation) {
    new AnnotationEditModal(this.app, annotation, async (newContent) => {
      annotation.content = newContent;
      await this.plugin.updateAnnotation(annotation);
      this.updatePreview();
      setTimeout(() => {
        this.plugin.forceRefreshHighlights();
      }, 50);
      new import_obsidian.Notice("\u6279\u6CE8\u5DF2\u66F4\u65B0");
    }).open();
  }
  async deleteAnnotation(annotation) {
    const confirmDelete = confirm("\u786E\u5B9A\u8981\u5220\u9664\u8FD9\u6761\u6279\u6CE8\u5417\uFF1F");
    if (!confirmDelete)
      return;
    try {
      await this.plugin.deleteAnnotation(annotation.id, annotation.sourceFile);
      this.updatePreview();
      this.plugin.forceRefreshHighlights();
      new import_obsidian.Notice("\u6279\u6CE8\u5DF2\u5220\u9664");
    } catch (error) {
      console.error("\u5220\u9664\u6279\u6CE8\u5931\u8D25:", error);
      new import_obsidian.Notice("\u5220\u9664\u6279\u6CE8\u5931\u8D25");
    }
  }
  // 设置图片悬停预览功能
  setupImageHoverPreview(container) {
    const images = container.querySelectorAll("img");
    images.forEach((img) => {
      var _a;
      img.style.display = "none";
      const imgLink = document.createElement("span");
      imgLink.className = "annotation-image-link";
      imgLink.textContent = "\u{1F5BC}\uFE0F \u56FE\u7247";
      imgLink.style.cursor = "pointer";
      imgLink.style.color = "var(--text-accent)";
      imgLink.style.textDecoration = "underline";
      imgLink.style.margin = "0 4px";
      let previewEl = null;
      imgLink.addEventListener("mouseenter", (e) => {
        if (previewEl)
          return;
        previewEl = document.createElement("div");
        previewEl.className = "annotation-image-preview";
        previewEl.style.cssText = `
					position: fixed;
					background: var(--background-primary);
					border: 1px solid var(--background-modifier-border);
					border-radius: 6px;
					padding: 8px;
					z-index: 10000;
					box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
					max-width: 300px;
					max-height: 200px;
					overflow: hidden;
				`;
        const previewImg = document.createElement("img");
        previewImg.src = img.src;
        previewImg.style.cssText = `
					max-width: 100%;
					max-height: 180px;
					object-fit: contain;
					border-radius: 4px;
				`;
        previewEl.appendChild(previewImg);
        const rect = imgLink.getBoundingClientRect();
        previewEl.style.left = `${rect.left}px`;
        previewEl.style.top = `${rect.bottom + 5}px`;
        if (rect.left + 300 > window.innerWidth) {
          previewEl.style.left = `${window.innerWidth - 320}px`;
        }
        if (rect.bottom + 200 > window.innerHeight) {
          previewEl.style.top = `${rect.top - 210}px`;
        }
        document.body.appendChild(previewEl);
      });
      imgLink.addEventListener("mouseleave", () => {
        if (previewEl) {
          previewEl.remove();
          previewEl = null;
        }
      });
      (_a = img.parentNode) == null ? void 0 : _a.insertBefore(imgLink, img);
    });
  }
  async onClose() {
  }
};
var AnnotationEditModal = class extends import_obsidian.Modal {
  constructor(app, annotation, onSubmit) {
    super(app);
    this.annotation = annotation;
    this.onSubmit = onSubmit;
    this.content = annotation.content;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u7F16\u8F91\u6279\u6CE8" });
    contentEl.createEl("p", {
      text: "\u9009\u4E2D\u5185\u5BB9:",
      cls: "annotation-selected-label"
    });
    const quoteEl = contentEl.createEl("blockquote", {
      text: this.annotation.selectedText.length > 100 ? this.annotation.selectedText.substring(0, 100) + "..." : this.annotation.selectedText,
      cls: "annotation-selected-text"
    });
    contentEl.createEl("p", {
      text: "\u6279\u6CE8\u5185\u5BB9:",
      cls: "annotation-content-label"
    });
    const textarea = contentEl.createEl("textarea", {
      cls: "annotation-textarea"
    });
    textarea.rows = 5;
    textarea.style.width = "100%";
    textarea.style.marginTop = "10px";
    textarea.placeholder = "\u5728\u6B64\u8F93\u5165\u60A8\u7684\u6279\u6CE8\u5185\u5BB9...";
    textarea.value = this.content;
    textarea.addEventListener("input", (e) => {
      this.content = e.target.value;
    });
    const buttonContainer = contentEl.createEl("div", {
      cls: "annotation-button-container"
    });
    buttonContainer.style.marginTop = "20px";
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.justifyContent = "flex-end";
    const cancelButton = buttonContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelButton.addEventListener("click", () => {
      this.close();
    });
    const saveButton = buttonContainer.createEl("button", {
      text: "\u4FDD\u5B58",
      cls: "mod-cta"
    });
    saveButton.addEventListener("click", () => {
      if (this.content.trim()) {
        this.onSubmit(this.content);
        this.close();
      } else {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u6279\u6CE8\u5185\u5BB9");
      }
    });
    textarea.focus();
    textarea.select();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AnnotationSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u6279\u6CE8\u63D2\u4EF6\u8BBE\u7F6E" });
    const folderSetting = new import_obsidian.Setting(containerEl).setName("\u6279\u6CE8\u6587\u4EF6\u5939").setDesc("\u6279\u6CE8\u6587\u4EF6\u5C06\u4FDD\u5B58\u5728\u6B64\u6587\u4EF6\u5939\u4E2D");
    let folderInput;
    folderSetting.addText((text) => {
      text.setPlaceholder("Annotations").setValue(this.plugin.settings.annotationFolder).onChange(async (value) => {
        let trimmedValue = value.trim();
        if (trimmedValue) {
          trimmedValue = trimmedValue.replace(/^[\/\\]+/, "");
          trimmedValue = trimmedValue.replace(/[\/\\]+$/, "");
        }
        if (trimmedValue) {
          const oldFolder = this.plugin.settings.annotationFolder;
          this.plugin.settings.annotationFolder = trimmedValue;
          await this.plugin.saveSettings();
          if (oldFolder !== trimmedValue) {
            await this.plugin.loadAnnotations();
            this.plugin.forceRefreshHighlights();
            new import_obsidian.Notice(`\u6279\u6CE8\u6587\u4EF6\u5939\u5DF2\u66F4\u6539\u4E3A: ${trimmedValue}`);
          }
        }
      });
      folderInput = text.inputEl;
      return text;
    });
    folderSetting.addButton((button) => {
      button.setButtonText("\u9009\u62E9\u6587\u4EF6\u5939").setTooltip("\u6D4F\u89C8\u5E76\u9009\u62E9\u6279\u6CE8\u6587\u4EF6\u5939").onClick(async () => {
        new FolderSuggestModal(this.app, async (folder) => {
          const folderPath = folder.path === "/" ? "" : folder.path;
          this.plugin.settings.annotationFolder = folderPath || "Annotations";
          await this.plugin.saveSettings();
          if (folderInput) {
            folderInput.value = this.plugin.settings.annotationFolder;
          }
          await this.plugin.loadAnnotations();
          this.plugin.forceRefreshHighlights();
          new import_obsidian.Notice(`\u6279\u6CE8\u6587\u4EF6\u5939\u5DF2\u8BBE\u7F6E\u4E3A: ${this.plugin.settings.annotationFolder}`);
        }).open();
      });
      return button;
    });
    new import_obsidian.Setting(containerEl).setName("\u9AD8\u4EAE\u989C\u8272").setDesc("\u6279\u6CE8\u6587\u5B57\u7684\u9AD8\u4EAE\u989C\u8272").addColorPicker((color) => color.setValue(this.plugin.settings.highlightColor).onChange(async (value) => {
      this.plugin.settings.highlightColor = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u663E\u793A\u6279\u6CE8\u9884\u89C8").setDesc("\u5728\u4FA7\u8FB9\u680F\u663E\u793A\u6279\u6CE8\u9884\u89C8\u9762\u677F").addToggle((toggle) => toggle.setValue(this.plugin.settings.showAnnotationPreview).onChange(async (value) => {
      this.plugin.settings.showAnnotationPreview = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u9884\u89C8\u9762\u677F\u4F4D\u7F6E").setDesc("\u6279\u6CE8\u9884\u89C8\u9762\u677F\u56FA\u5B9A\u5728\u53F3\u4FA7\u529F\u80FD\u533A").addDropdown((dropdown) => dropdown.addOption("right", "\u53F3\u4FA7\u529F\u80FD\u533A").setValue("right").setDisabled(true));
  }
};
var FolderSuggestModal = class extends import_obsidian.Modal {
  constructor(app, onChoose) {
    super(app);
    this.folders = [];
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("\u9009\u62E9\u6279\u6CE8\u6587\u4EF6\u5939");
    this.folders = this.getAllFolders();
    const searchContainer = contentEl.createDiv("folder-search-container");
    const searchInput = searchContainer.createEl("input", {
      type: "text",
      placeholder: "\u641C\u7D22\u6587\u4EF6\u5939...",
      cls: "folder-search-input"
    });
    searchInput.style.width = "100%";
    searchInput.style.marginBottom = "10px";
    searchInput.style.padding = "5px";
    const listContainer = contentEl.createDiv("folder-list-container");
    listContainer.style.maxHeight = "300px";
    listContainer.style.overflow = "auto";
    const renderFolders = (filter = "") => {
      listContainer.empty();
      const createNewItem = listContainer.createDiv("folder-list-item");
      createNewItem.style.padding = "8px";
      createNewItem.style.cursor = "pointer";
      createNewItem.style.borderBottom = "1px solid var(--background-modifier-border)";
      createNewItem.style.fontWeight = "bold";
      createNewItem.style.color = "var(--text-accent)";
      createNewItem.textContent = filter ? `\u521B\u5EFA\u65B0\u6587\u4EF6\u5939 "${filter}"` : "+ \u521B\u5EFA\u65B0\u6587\u4EF6\u5939";
      createNewItem.addEventListener("click", async () => {
        const folderName = filter || "Annotations";
        try {
          const newFolder = await this.app.vault.createFolder(folderName);
          this.onChoose(newFolder);
          this.close();
        } catch (error) {
          new import_obsidian.Notice("\u521B\u5EFA\u6587\u4EF6\u5939\u5931\u8D25\uFF0C\u53EF\u80FD\u5DF2\u5B58\u5728");
        }
      });
      createNewItem.addEventListener("mouseover", () => {
        createNewItem.style.backgroundColor = "var(--background-modifier-hover)";
      });
      createNewItem.addEventListener("mouseout", () => {
        createNewItem.style.backgroundColor = "";
      });
      const filteredFolders = this.folders.filter((folder) => folder.path.toLowerCase().includes(filter.toLowerCase())).sort((a, b) => a.path.localeCompare(b.path));
      for (const folder of filteredFolders) {
        const item = listContainer.createDiv("folder-list-item");
        item.style.padding = "8px";
        item.style.cursor = "pointer";
        item.style.borderBottom = "1px solid var(--background-modifier-border)";
        const folderName = folder.path === "/" ? "\u6839\u76EE\u5F55 (/)" : folder.path;
        item.textContent = folderName;
        item.addEventListener("click", () => {
          this.onChoose(folder);
          this.close();
        });
        item.addEventListener("mouseover", () => {
          item.style.backgroundColor = "var(--background-modifier-hover)";
        });
        item.addEventListener("mouseout", () => {
          item.style.backgroundColor = "";
        });
      }
      if (filteredFolders.length === 0 && !filter) {
        const emptyMsg = listContainer.createDiv("folder-list-empty");
        emptyMsg.textContent = "\u6CA1\u6709\u627E\u5230\u6587\u4EF6\u5939";
        emptyMsg.style.padding = "20px";
        emptyMsg.style.textAlign = "center";
        emptyMsg.style.color = "var(--text-muted)";
      }
    };
    renderFolders();
    searchInput.addEventListener("input", (e) => {
      renderFolders(e.target.value);
    });
    searchInput.focus();
    const buttonContainer = contentEl.createDiv("modal-button-container");
    buttonContainer.style.marginTop = "15px";
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "flex-end";
    buttonContainer.style.gap = "10px";
    const cancelButton = buttonContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelButton.addEventListener("click", () => {
      this.close();
    });
  }
  getAllFolders() {
    const folders = [];
    const root = this.app.vault.getRoot();
    folders.push(root);
    const traverse = (folder) => {
      for (const child of folder.children) {
        if (child instanceof import_obsidian.TFolder) {
          folders.push(child);
          traverse(child);
        }
      }
    };
    traverse(root);
    return folders;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
